genus_to_group <- c(

  "Ribes" = "bush berries",
  "Rubus" = "bush berries",
  "Vaccinium" = "bush berries",
  "Fragaria" = "strawberries",
  "Malus" = "apples",
  "Pyrus" = "pears",
  "Vitis" = "wine grapes",
  "Persea" = "avocados",
  "Olea" = "olives",
  "Juglans" = "walnuts",
  "Pistacia" = "pistachios",
  "Punica" = "pomegranates",
  "Phoenix" = "dates",
  "Zea" = "corn sorghum sudan",
  "Sorghum" = "corn sorghum sudan",
  "Triticum" = "wheat",
  "Oryza" = "rice",
  "Zizania" = "wild rice",
  "Gossypium" = "cotton",
  "Helianthus" = "sunflowers",
  "Medicago" = "alfalfa and alfalfa mixtures",
  "Vigna" = "beans",
  "Glycine" = "beans",
  "Phaseolus" = "beans",
  "Spinacia" = "lettuce or leafy greens",
  "Brassica" = "cole crops",
  "Daucus" = "carrots",
  "Cucurbita" = "melons squash and cucumber",
  "Cucumis" = "melons squash and cucumber",
  "Capsicum" = "peppers",
  "Solanum" = "potatoes",
  "Ipomoea" = "potato or sweet potato",
  "Allium" = "onions and garlic",
  "Lactuca" = "lettuce or leafy greens",
  "Prunus" = "miscellaneous deciduous",
  
  # New mappings from your species list ---------------------------------------
  
  # GRASSES → miscellaneous grasses (P6)
  "Agrostis" = "miscellaneous grasses",
  "Anthoxanthum" = "miscellaneous grasses",
  "Cynosurus" = "miscellaneous grasses",
  "Deschampsia" = "miscellaneous grasses",
  "Dactylis" = "miscellaneous grasses",
  "Festuca" = "miscellaneous grasses",
  "Holcus" = "miscellaneous grasses",
  "Lolium" = "miscellaneous grasses",
  "Phleum" = "miscellaneous grasses",
  "Poa" = "miscellaneous grasses",
  "Trisetum" = "miscellaneous grasses",
  "Alopecurus" = "miscellaneous grasses",
  "Arrhenatherum" = "miscellaneous grasses",
  "Calamagrostis" = "miscellaneous grasses",
  "Elymus" = "miscellaneous grasses",
  "Eragrostis" = "miscellaneous grasses",
  "Muhlenbergia" = "miscellaneous grasses",
  "Panicum" = "miscellaneous grasses",
  "Paspalum" = "miscellaneous grasses",
  "Schizachyrium" = "miscellaneous grasses",
  "Sporobolus" = "miscellaneous grasses",
  "Stipa" = "miscellaneous grasses",
  "Bouteloua" = "miscellaneous grasses",
  "Hilaria" = "miscellaneous grasses",
  "Nardus" = "miscellaneous grasses",
  "Leersia" = "miscellaneous grasses",
  "Microstegium" = "miscellaneous grasses",
  "Chasmanthium" = "miscellaneous grasses",
  
  # FORBS & HERBACEOUS PLANTS → mixed pasture (P3)
  "Achillea" = "mixed pasture",
  "Agoseris" = "mixed pasture",
  "Ambrosia" = "mixed pasture",
  "Androsace" = "mixed pasture",
  "Antennaria" = "mixed pasture",
  "Arenaria" = "mixed pasture",
  "Artemisia" = "mixed pasture",
  "Astragalus" = "mixed pasture",  # LEGUME
  "Bidens" = "mixed pasture",
  "Campanula" = "mixed pasture",
  "Centaurea" = "mixed pasture",
  "Cerastium" = "mixed pasture",
  "Chenopodium" = "mixed pasture",
  "Cirsium" = "mixed pasture",
  "Convolvulus" = "mixed pasture",
  "Cosmos" = "mixed pasture",
  "Draba" = "mixed pasture",
  "Drymaria" = "mixed pasture",
  "Echeandia" = "mixed pasture",
  "Epilobium" = "mixed pasture",
  "Eriogonum" = "mixed pasture",
  "Erigeron" = "mixed pasture",
  "Erodium" = "mixed pasture",
  "Euphorbia" = "mixed pasture",
  "Filipendula" = "mixed pasture",
  "Gaillardia" = "mixed pasture",
  "Galium" = "mixed pasture",
  "Geranium" = "mixed pasture",
  "Gutierrezia" = "mixed pasture",
  "Heliomeris" = "mixed pasture",
  "Helianthella" = "mixed pasture",
  "Hieracium" = "mixed pasture",
  "Houstonia" = "mixed pasture",
  "Hymenoxys" = "mixed pasture",
  "Hymenopappus" = "mixed pasture",
  "Hypochaeris" = "mixed pasture",
  "Ipomopsis" = "mixed pasture",
  "Iris" = "mixed pasture",
  "Koeleria" = "miscellaneous grasses",
  "Laennecia" = "mixed pasture",
  "Lepidium" = "mixed pasture",
  "Linum" = "mixed pasture",
  "Linaria" = "mixed pasture",
  "Lithospermum" = "mixed pasture",
  "Lobelia" = "mixed pasture",
  "Ludwigia" = "mixed pasture",
  "Nama" = "mixed pasture",
  "Oenothera" = "mixed pasture",
  "Oxalis" = "mixed pasture",
  "Oxytropis" = "mixed pasture",  # LEGUME
  "Packera" = "mixed pasture",
  "Penstemon" = "mixed pasture",
  "Phlox" = "mixed pasture",
  "Plantago" = "mixed pasture",
  "Polygonum" = "mixed pasture",
  "Portulaca" = "mixed pasture",
  "Potentilla" = "mixed pasture",
  "Pseudognaphalium" = "mixed pasture",
  "Quercus" = "miscellaneous deciduous",
  "Rosa" = "miscellaneous deciduous",
  "Rumex" = "mixed pasture",
  "Saxifraga" = "mixed pasture",
  "Sanguisorba" = "mixed pasture",
  "Senecio" = "mixed pasture",
  "Solidago" = "mixed pasture",
  "Symphyotrichum" = "mixed pasture",
  "Taraxacum" = "mixed pasture",
  "Thalictrum" = "mixed pasture",
  "Townsendia" = "mixed pasture",
  "Tragopogon" = "mixed pasture",
  "Trifolium" = "mixed pasture",   # LEGUME
  "Verbascum" = "mixed pasture",
  "Verbena" = "mixed pasture",
  "Vicia" = "mixed pasture",       # LEGUME
  "Viola" = "mixed pasture",
  "Dieteria" = "mixed pasture",
  "Xanthisma" = "mixed pasture",
  
  # WETLAND / SEDGE / RUSH GROUP → mixed pasture (neutral)
  "Carex" = "mixed pasture",
  "Cyperus" = "mixed pasture",
  "Eleocharis" = "mixed pasture",
  "Scirpus" = "mixed pasture",
  "Juncus" = "mixed pasture",
  
  # TREES → miscellaneous deciduous (D10)
  "Pinus" = "miscellaneous deciduous",
  "Larix" = "miscellaneous deciduous",
  "Populus" = "miscellaneous deciduous",
  "Fraxinus" = "miscellaneous deciduous",
  "Ailanthus" = "miscellaneous deciduous",
  "Caragana" = "miscellaneous deciduous",
  "Ceanothus" = "miscellaneous deciduous",
  
  # SHRUBS
  "Corydalis" = "mixed pasture",
  "Eremogone" = "mixed pasture",
  "Campanula" = "mixed pasture",
  
  # EXOTIC CROPS
  "Coffea" = "miscellaneous field",
  
  # UNKNOWN
  "unknown" = "miscellaneous field"
)

#most of the miscellaneous grasses, pasture, and field species are for root CN


map_species_to_group <- function(species_vec) {
  genus <- sub("^(\\w+).*", "\\1", species_vec)   # take first word
  group <- genus_to_group[genus]                  # lookup
  group[is.na(group)] <- "NA"                     # default
  return(unname(group))
}

