# PEcAn workflow (web/workflow.R) {#workflow}

- How the workflow works
- How each module is called
- How to do outside of web interface
- Link to "folder structure" section below for detailed descriptions


<div style="width: 640px; height: 960px; margin: 10px; position: relative;"><iframe allowfullscreen frameborder="0" style="width:640px; height:480px" src="https://www.lucidchart.com/documents/embeddedchart/93dca2c6-63cb-4df4-b68c-29590d1836fc" id="uAv44V~qLSWE"></iframe></div>

## Read Settings {#workflow-readsettings}

(TODO: Under construction...)

## Input Conversions {#workflow-input}

## Input Data {#workflow-input-data}

Models require input data as drivers, parameters, and boundary conditions. In order to make a variety of data sources that have unique formats compatible with models, conversion scripts are written to convert them into a PEcAn standard format. That format is a netcdf file with variables names and specified to our standard variable table.

Within the PEcAn repository, code pertaining to input conversion is in the MODULES directory under the data.atmosphere and data.land directories. 

## Initial Conditions {#workflow-input-initial}

### CONUS (NEON/FIA/BADM) Initial Conditions.

To convert initial condition data into the PEcAn Standard and then into the model formats we follow three main steps:

  1. Downloading vegetation info
    -converting the vegetation info into .rd file format
  2. Creating ensemble members based on veg file 
    -resamples veg file to create ensmeble members
  3. Converting ensemble members to model specific format

Common Questions regarding IC Data:

How do I know if my data product is supported by ic_process workflow?
  -The current data products supported by ic_process are: NEON, FIA, and BADM. That said you if your vegetation files are registered with BETY and abide by the BETY formats and column names you will be able to use ic_process to create ensemble members and convert the ensemble members to model specific format. See section 6.3.3 for more info. 
Can I use ic_process outside of the PEcAn workflow?
  -Short answer is yes, ic_process can be called as a function all by itself outside of do_conversions.
What about soil initial conditions?
  -Please reference section 6.3.6 for more info.

ic_process workflow:

Required inputs for ic_process are: settings object with </pft> and </poolinitcond> sections (see pecan.xml section for more info), dir or location where you would to store the output files, input object that contains all info from settings$run$inputs$poolinitcond, and the overwrite setting the default is overwrite = FALSE.

get_veg_module()
This function will either download your vegetation info from: NEON_veg, FIA, BADM sources or query BETY for existing veg files previously downloaded. The input and dbfile ids of your veg file are then added to a list getveg.id.

ens_veg_module()
This function will create ensemble member ncdf files by resampling the veg file supplied in getveg.id. 

put_veg_module()
This function will convert the ensemble member ncdf files into model specific format. Currently the supported models are ED2 and SIPNET. 

### North America (NA) Initial Conditions.

To create initial condition files across North America, you will need to strictly follow the script located at `~/pecan/modules/assim.sequential/inst/anchor/IC_prep_anchorSites.Rmd`. Within the script we will be following those main steps:
  1. Loading `settings.xml` file and specify paths.
  2. Downloading/extracting estimations of four major carbon/water pools (leaf, wood, soil C, soil water) into by-site and by-ensemble tables.
  3. Doing unit conversion. For each ensemble of each site, we will be preparing the `poolinfo` object consisting of converted pool estimations.
  4. We will finally be writing the NC files through the `PEcAn.SIPNET::veg2model.SIPNET` function.
  5. Within the loop, we will store the NC file paths into the settings object and rewrite the settings into the XML file to the destination.

Within the script we proposed the following new datasets for handling the NA initial condition preparations:

  1. The leaf carbon is initialized with MODIS LAI observations and the SLA for the corresponding PFT.
  2. The above ground biomass (AGB) is initialized with the 2010 global AGB map (DOI: https://doi.org/10.3334/ORNLDAAC/1763).
  3. The soil moisture (SM) is initialized with the SM estimations starting from 1978 (DOI: 10.24381/cds.d7782f18).
  4. The soil organic carbon (SOC) is initialized with ISCN SOC estimations (data already prepared on PEcAn, use `PEcAn.data.land::iscn_soc` to load) based on the level 2 ecoregion map (pre-downloaded using the following link: https://www.epa.gov/eco-research/ecoregions).

## Meteorological Data {#workflow-met}

To convert meterological data into the PEcAn Standard and then into model formats we follow four main steps:
  
  1. Downloading raw data
    - [Currently supported products]()
    - Example Code
  2. Converting raw data into a CF standard 
    - Example Code 
  3. Downscaling and gapfilling
    - Example Code 
  4. Coverting to Model Specific format
    - Example Code 

Common Questions regarding Met Data: 

How do I add my Meterological data product to PEcAn?
How do I use PEcAn to convert Met data outside the workflow?


The main script that handles Met Processing, is [`met.process`](https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/met.process.R). It acts as a wrapper function that calls individual modules to facilitate the processing of meteorological data from it's original form to a pecan standard, and then from that standard to model specific formats. It also handles recording these processes in the BETY database.

  1. Downloading raw data
    - [Available Meteorological Drivers](#met-drivers)
    - Example Code to download [Ameriflux data](https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/download.AmerifluxLBL.R)
  2. Converting raw data into a CF standard (if needed)
    - Example Code to [convert from raw csv to CF standard](https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/met2CF.csv.R)
  3. Downscaling and gapfilling(if needed)
    - Example Code to [gapfill](https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/metgapfill.R)
  4. Coverting to Model Specific format
    - Example Code to [convert Standard into Sipnet format](https://github.com/PecanProject/pecan/blob/develop/models/sipnet/R/met2model.SIPNET.R)
    

### Downloading Raw data (Description of Process) {#workflow-met-download}
  
  Given the information passed from the pecan.xml met.process will call the `download.raw.met.module` to facilitate the execution of the necessary functions to download raw data.

```xml
  <met>
    <source>AmerifluxLBL</source>
    <output>SIPNET</output>
    <username>pecan</username>
  </met>
```
  
### Converting raw data to PEcAn standard {#workflow-met-standard}

### Downscaling and gapfilling (optional) {#workflow-met-downscale}

### Converting from PEcAn standard to model-specific format {#workflow-met-model}

## Input phenological Data {#workflow-input-phenology}

To enable the use of MODIS phenology data (MODIS Land Cover Dynamics (MCD12Q2)) to update the phenological parameters (leaf-on date) and (leaf-off date) at each restart timepoint: 
 1. Generate the phenological parameter CSV file by running `PEcAn.data.remote::extract_phenology_MODIS`.
 2. Provide the generated phenological parameter CSV file to `settings$run$inputs$leaf_phenology$path`.

## Traits {#workflow-traits}

(TODO: Under construction)

## Meta Analysis {#workflow-metaanalysis}

(TODO: Under construction)

## Model Configuration {#workflow-modelconfig}
To enable the state data assimilation with sub-annual data, default `conflict` in `model2netcdf` should be `TRUE`. 

(TODO: Under construction)

## Run Execution {#workflow-modelrun}

(TODO: Under construction)

## Post Run Analysis {#workflow-postrun}

(TODO: Under construction)
## Advanced Analysis {#workflow-advanced}

(TODO: Under construction)

