# Installing and configuring Shiny for PEcAn
authors - Alexey Shiklomanov
        - Rob Kooper

**NOTE: Instructions are only tested for CentOS 6.5 and Ubuntu 16.04**
**NOTE: Pretty much every step here requires root access.**

## Install the Shiny R package and Shiny server

Follow the instructions on the [Shiny download page][shiny-download] for the operating system you are using.

[shiny-download]: https://www.rstudio.com/products/shiny/download-server/

## Modify the shiny configuration file

The Shiny configuration file is located in `/etc/shiny-server/shiny-server.conf`. Comment out the entire file and add the following, replacing `<username>` with your user name and `<location>` with the URL location you want for your app. This will allow you to run Shiny apps from your web browser at https://your.server.edu/shiny/your-location

```
run as shiny;
server {
    listen 3838;
    location /<location>/ {
        run as <username>;
        site_dir /path/to/your/shiny/app;
        log_dir /var/log/shiny-server;
        directory_index on;
    }
}
```

For example, my configuration on the old test-pecan looks like this.

```
run as shiny;
server {
    listen 3838;
    location /ashiklom/ {
        run as ashiklom;
        site_dir /home/ashiklom/fs-data/pecan/shiny/;
        log_dir /var/log/shiny-server;
        directory_index on;
    }
}
```

...and I can access my Shiny apps at, for instance, https://test-pecan.bu.edu/shiny/ashiklom/workflowPlots.

You can add as many `location <loc> { ... }` fields as you would like.

```
run as shiny;
server {
    listen 3838;
    location /ashiklom/ {
        ...
    }
    location /bety/ {
        ...
    }
}
```

If you change the configuration, for example to add a new location, you will need to restart Shiny server.
*If you are setting up a new instance of Shiny*, skip this step and continue with the guide, since there are a few more steps to get Shiny working.
*If there is an instance of Shiny already running*, you can restart it with:

```
## On CentOS
sudo service shiny-server stop
sudo service shiny-server start

## On Ubuntu
sudo systemctl stop shiny-server.service
sudo systemctl start shiny-server.service
```

## Set the Apache proxy

Create a file with the following name, based on the version of the operating system you are using:

* Ubuntu 16.04 (pecan1, pecan2, test-pecan) -- `/etc/apache2/conf-available/shiny.conf`
* CentOS 6.5 (psql-pecan) -- `/etc/httpd/conf.d/shiny.conf`

Into this file, add the following:

```
ProxyPass           /shiny/ http://localhost:3838/
ProxyPassReverse    /shiny/ http://localhost:3838/
RedirectMatch permanent ^/shiny$ /shiny/
```

### **Ubuntu only:** Enable the new shiny configuration

```
sudo a2enconf shiny
```

This will create a symbolic link to the newly created `shiny.conf` file inside the `/etc/apache2/conf-enabled` directory.
You can do `ls -l /etc/apache2/conf-enabled` to confirm that this worked.

## Enable and start the shiny server, and restart apache

### On CentOS

```
sudo ln -s /opt/shiny-server/config/init.d/redhat/shiny-server /etc/init.d
sudo service shiny-server stop
sudo service shiny-server start
sudo service httpd restart
```

You can check that Shiny is running with `service shiny-server status`.

### On Ubuntu

Enable the Shiny server service.
This will make sure Shiny runs automatically on startup.

```
sudo systemctl enable shiny-server.service
```

Restart Apache.

```
sudo apachectl restart
```

Start the Shiny server.

```
sudo systemctl start shiny-server.service
```

If there are problems, you can stop the `shiny-server.service` with...

```
sudo systemctl stop shiny-server.service
```

...and then use `start` again to restart it.


## Troubleshooting

Refer to the log files for shiny (`/var/log/shiny-server.log`) and httpd (on CentOS, `/var/log/httpd/error-log`; on Ubuntu, `/var/log/apache2/error-log`).



## Further reading

* [Shiny server configuration reference](http://docs.rstudio.com/shiny-server/)

