# Input Conversion

Three Types of data conversions are discussed below: Meteorological data, Vegetation data, and Soil data. Each section provides instructions on how to convert data from their raw formats into a PEcAn standard format, whether it be from a database or if you have raw data in hand.

## Meterological Data conversion

### Adding a function to PEcAn to convert a met data source
In general, you will need to write a function to download the raw met data and one to convert it to the PEcAn standard.

Downloading raw data function are named `download.<source>.R`. These functions are stored within the PEcAn directory: [`/modules/data.atmosphere/R`](https://github.com/PecanProject/pecan/tree/develop/modules/data.atmosphere/R). 

Conversion function from raw to standard are named  `met2CF.<source>.R`. These functions are stored within the PEcAn directory: [`/modules/data.atmosphere/R`](https://github.com/PecanProject/pecan/tree/develop/modules/data.atmosphere/R).

Current Meteorological products that are coupled to PEcAn can be found in our [Available Meterological Drivers] page.

Note: Unless you are also adding a new model, you will not need to write a script to convert from PEcAn standard to PEcAn models. Those conversion scripts are written when a model is added and can be found within each model's PEcAn directory.

### Dimensions:


|CF standard-name | units |
|:------------------------------------------|:------|
| time | days since 1700-01-01 00:00:00 UTC|
| longitude | degrees_east|
| latitude |degrees_north|

General Note: dates in the database should be date-time (preferably with timezone), and datetime passed around in PEcAn should be of type POSIXct.


### The variable names should be `standard_name`

| CF standard-name                          | units | bety         | isimip       | cruncep | narr  | ameriflux |
|:------------------------------------------|:------|:-------------|:-------------|:--------|:------|:----------|
| **air_temperature**                       | K     | airT         | tasAdjust    | tair    | air   | TA (C)    |
| air_temperature_max                       | K     |              | tasmaxAdjust | NA      | tmax  |           |
| air_temperature_min                       | K     |              | tasminAdjust | NA      | tmin  |           |
| **air_pressure**                          | Pa    | air_pressure |              |         |       | PRESS (KPa) |
| mole_fraction_of_carbon_dioxide_in_air    | mol/mol |            |              |         |       | CO2       |
| moisture_content_of_soil_layer            | kg m-2 |             |              |         |       |           |
| soil_temperature                          | K     | soilT        |              |         |       | TS1 *(NOT DONE)* |
| relative_humidity                         | % | relative_humidity | rhurs       | NA      | rhum  | RH        |
| **specific_humidity**                     | 1 | specific_humidity | NA          | qair    | shum  | CALC(RH)  |
| water_vapor_saturation_deficit            | Pa    | VPD          |              |         |       | VPD *(NOT DONE)*     |
| **surface_downwelling_longwave_flux_in_air** | W m-2 | same      | rldsAdjust   | lwdown  | dlwrf | Rgl       |
| **surface_downwelling_shortwave_flux_in_air**| W m-2 |solar_radiation|rsdsAdjust| swdown  | dswrf | Rg        |
| surface_downwelling_photosynthetic_photon_flux_in_air | mol m-2 s-1 | PAR |     |         |       | PAR *(NOT DONE)*          |
| **precipitation_flux**                    |  kg m-2 s-1 | cccc   | prAdjust     | rain    | acpc  | PREC (mm/s)          |
|                                           | degrees | wind_direction |          |         |       | WD        |
| wind_speed                                | m/s   | Wspd         |              |         |       | WS        |
| **eastward_wind**                         | m/s   | eastward_wind |             |         |       | CALC(WS+WD) |
| **northward_wind**                        | m/s   | northward_wind |            |         |       | CALC(WS+WD) |

* preferred variables indicated in bold
* wind_direction has no CF equivalent and should not be converted, instead the met2CF functions should convert wind_direction and wind_speed to eastward_wind and northward_wind
* standard_name is CF-convention standard names
* units can be converted by udunits, so these can vary (e.g. the time denominator may change with time frequency of inputs)
* soil moisture for the full column, rather than a layer, is soil_moisture_content
* A full list of PEcAn standard variable names, units and dimensions can be found here: https://github.com/PecanProject/pecan/blob/develop/base/utils/data/standard_vars.csv


For example, in the [MsTMIP-CRUNCEP](https://www.betydb.org/inputs/280) data, the variable `rain` should be `precipitation_rate`.
We want to standardize the units as well as part of the `met2CF.<product>` step. I believe we want to use the CF "canonical" units but retain the MsTMIP units any time CF is ambiguous about the units.

The key is to process each type of met data (site, reanalysis, forecast, climate scenario, etc) to the exact same standard. This way every operation after that (extract, gap fill, downscale, convert to a model, etc) will always have the exact same inputs. This will make everything else much simpler to code and allow us to avoid a lot of unnecessary data checking, tests, etc being repeated in every downstream function.

### Adding Single-Site Specific Meteorological Data

Perhaps you have meteorological data specific to one site, with a unique format that you would like to add to PEcAn. Your steps would be to:
  1. write a script or function to convert your files into the netcdf PEcAn standard
  2. insert that file as an input record for your site following these [instructions](How to Insert new Input Data)
  
### Processing Met data outside of the workflow using PEcAn functions

Perhaps you would like to obtain data from one of the sources coupled to PEcAn on its own. To do so you can run PEcAn functions on their own. 

#### Example 1: Processing data from a database 

Download Amerifluxlbl from Niwot Ridge for the year 2004:

```
raw.file <-PEcAn.data.atmosphere::download.AmerifluxLBL(sitename = "US-NR1", 
                                             outfolder = ".", 
                                             start_date = "2004-01-01", 
                                             end_date = "2004-12-31")
```

Using the information returned as the object `raw.file` you will then convert the raw files into a standard file.

Open a connection with BETY. You may need to change the host name depending on what mahcine you are hosting BETY. You can find the hostname listed in the machines table of BETY.

```

bety <- dplyr::src_postgres(dbname   = 'bety', 
                            host ='localhost', 
                            user     = "bety", 
                            password = "bety")
                            
bety$con <- con
```
Next you will set up the arguments for the function
```
in.path <- '.'
in.prefix <- raw.file$dbfile.name
outfolder <- '.'
format.id <- 5000000002
format <- PEcAn.DB::query.format.vars(format.id=format.id,bety = bety)
lon <- 105.54
lat <- 40.03
format$time_zone <- "America/Chicago"
```
Note: The format.id can be pulled from the BETY database if you know the format of the raw data. Once 


```
PEcAn.data.atmosphere::met2CF.csv(in.path = in.path, 
                                  in.prefix ="US-NR1_CF", 
                                  outfolder = ".", 
                                  start_date ="2004-01-01",
                                  end_date = "2004-01-01",
                                  lat= lat,
                                  lon = lon,
                                  format = format) 
```
Note: The format.id is specific to the format type of the raw data. You can look up the format id in the Bety database. 

Example 2: Processing data from data already in hand 

If you have Met data already in hand and you would like to convert into the PEcAn standard follow these instructions.

Use met2CF.csv to 


```
```

## Vegetation Data

Vegetation data will be required to parameterize your model. In these examples we will go over how to produce a standard initial condition file.

The main function to process cohort data is the `ic.process.R` function. As of now however, if you require pool data you will run a seperate function, `pool_ic_list2netcdf.R`.

Example 1: Raw data from a database

If your data is coming from a datbase (ex.FIA) the <inputs> section of your pecan.xml will need to look like the following:
```
paste inputs section here
```
From here you read in the pecan.xml to obtain a settings object
```
settings<- 

```
You can then execute the `ic.process` function to convert data into a standard Rds file:

```
ic.process(settings, input, dir, overwrite = FALSE)

```

Example 2: Raw data in hand

You will first need to update the BETY database with the appropriate records. A file record with location of the raw file, a format record with requisite meta data information about the structure of the file, and then an input record what has the file and format record assiciated with it. Instructions on how to do that can be found here [How to Insert new Input Data].

Once that part is complete, you will need that input id in the pecan.xml. Edit your xml to look like this:

```
```
Read in settings 

```
ic.process(settings, input, dir, overwrite = FALSE)

```




If you have pool vegetation data, you'll need the [`pool_ic_list2netcdf.R`](https://github.com/PecanProject/pecan/blob/develop/modules/data.land/R/pool_ic_list2netcdf.R) function to convert the pool data into PEcAn
standard.

```


```

## Soil Data

In order to process Soil Data 



