### Developer's Guide

This section is geared toward those wishing to contribute to the PEcAn project. We welcome anyone wishing to do so. These are the topics covered in this section:

#### Contributing, Bug reports, Etc.
* [Reporting Bugs and Requesting Features](Github-issues.md)
    * [Overview](Github-issues.md#overview)
    * [Reporting a bug](Github-issues.md#reporting-a-bug)
    * [Requesting a feature](Github-issues.md#requesting-a-feature)
    * [Closing an issue](Github-issues.md#closing-an-issue)
    * [When to submit an issue?](Github-issues.md#when-to-submit-an-issue)
* [Using Github and Git](Using-Git.md)
    * [GIT and GitHub Overview](Using-Git.md#git-and-github-overview)
    * [Milestones, Issues, Tasks](Using-Git.md#milestones-isues-tasks)
    * [Quick and Easy](Using-Git.md#quick-and-easy)
    * [Recommended Git Workflow](Using-Git.md#recommended-git-workflow)
    * [Before any work is done](Using-Git.md#before-any-work-is-done)
    * [During development](Using-Git.md#during-development)
    * [Basic Workflow](Using-Git.md#basic-workflow)
    * [Advanced Workflow: A new branch for each change](Using-Git.md#advanced-workflow-a-new-brach-for-each-change)
    * [After pull request is merged](Using-Git.md#after-pull-request-is-merged)
    * [Link commits to issues](Using-Git.md#link-commits-to-issues)
    * [For PEcAn](Using-Git.md#for-pecan)
    * [Committing Changes Using Pull Requests](Using-Git.md#committng-changes-using-pull-requests)
    * [Other Useful Git Commands](Using-Git.md#other-useful-git-commands)
    * [Tags](Using-Git.md#tags)
    * [Git + Rstudio](Using-Git.md#git--rstudio)
    * [Creating a Read-only version](Using-Git.md#creating-a-read-only-version)
    * [For development](Using-Git.md#for-development)
    * [References](Using-Git.md#references)
* [PEcAn Directory Structure](Directory-structure.md)
#### Adding or Extending Modules
* [Adding Ecosystem Model](Adding-an-Ecosystem-Model.md)
    * [PEcAn Database](Adding-an-Ecosystem-Model.md#pecan-database)
    * [Define MODEL_TYPE](Adding-an-Ecosystem-Model.md#define-modeltype)
    * [MACHINE](Adding-an-Ecosystem-Model.md#machine)
    * [MODEL](Adding-an-Ecosystem-Model.md#model)
    * [FORMATS](Adding-an-Ecosystem-Model.md#formats)
    * [Formats -> Variables](Adding-an-Ecosystem-Model.md#formats-variables)
    * [MODEL_TYPE -> Formats](Adding-an-Ecosystem-Model.md#modeltype-formats)
    * [INPUTS](Adding-an-Ecosystem-Model.md#inputs)
    * [PFTS (Plant Functional Types)](Adding-an-Ecosystem-Model.md#pfts-plant-functional-types)
    * [Species](Adding-an-Ecosystem-Model.md#species)
    * [PRIORS](Adding-an-Ecosystem-Model.md#priors)
    * [Interface Modules](Adding-an-Ecosystem-Model.md#interface-modules)
    * [Setting up the module directory (required)](Adding-an-Ecosystem-Model.md#setting-up-the-module-directory-required)
    * [DESCRIPTION](Adding-an-Ecosystem-Model.md#description)
    * [NAMESPACE](Adding-an-Ecosystem-Model.md#namespace)
    * [Building the package](Adding-an-Ecosystem-Model.md#building-the-package)
    * [write.config.MODEL (required)](Adding-an-Ecosystem-Model.md#write)
    * [Output Conversions](Adding-an-Ecosystem-Model.md#output-conversions)
    * [met2model.MODEL](Adding-an-Ecosystem-Model.md#met2model-model)
    * [Commit changes](Adding-an-Ecosystem-Model.md#commit-changes)
* [Adding an Input Converter](Adding-an-Input-Converter.md)
* [DART data assimilation](../users_guide/advanced_users_guide/DART_state_data_assimilation.md)
#### Advanced Installation
* [Installing PEcAn](Installing-PEcAn.md)
    * [Installing Prerequisites](Installing-PEcAn.md#installing-prerequisites)
    * [Install models](Installing-PEcAn.md#install-models)
    * [Installing PEcAn](Installing-PEcAn.md#installing-pecan)
    * [Installing BETY](Installing-PEcAn.md#installing-bety)
    * [Install Database + Data](Installing-PEcAn.md#install-database-data)
    * [Installing BETYdb Web Application](Installing-PEcAn.md#installing-betydb-web-application)
    * [PEcAn Testrun](Installing-PEcAn.md#pecan-testrun)
* [PEcAn in the Cloud](../PEcAn-in-the-Cloud.md)
* [VM Creation](VM-Creation.md)
* [PEcAn Configuration and Settings Files](Configuration-Files.md)
    * [PEcAn Configuration Files](Configuration-Files.md#pecan-configuration-files)
    * [Model-specific configuration files](Configuration-Files.md#model-specific-configuration-files)
#### R Development
* [Coding Style](Coding_style.md)
* [Documentation](Roxygen2.md)
* [Testing](Testing.md)
* [Package Data](Package-data.md)
* [Logging, Warnings, and Error Messages](Logging.md)
* [Installing Data](Installing-PEcAn-Data.md)
    * [Site Information](Installing-PEcAn-Data.md#site-information)
    * [FIA database](Installing-PEcAn-Data.md#fia-database)
    * [Flux Camp](Installing-PEcAn-Data.md#flux-camp)
    * [Harvard for ED tutorial](Installing-PEcAn-Data.md#harvard-fpr-ed-tutorial)
#### Inputs
* [Inputs](Data-Formats.md)
* [Standard Names](Adding-an-Input-Converter.md)
