### Contributing, Bug reports, Etc

* [[Code of Conduct]]
* [[Reporting bugs or requesting features | Github issues]]
* [[Using GitHub and Git | Using Git]] to get a copy of the latest development code and/or submit changes to the main repository
* [[PEcAn Directory Structure | Directory Structure]]


### Adding or Extending Modules

* [[Adding an Ecosystem Model]]
* [[Adding an Input Converter]]
* [[Implementing state data assimilation]]

### Advanced Installation

* [[Installing PEcAn]] on a server
* Install [[PEcAn in the Cloud]] (e.g. Amazon Web Services [AWS])
* [[VM Creation]] documentation
* [[PEcAn Configuration and Settings Files | Configuration Files]]

### R Development

The pages listed below provide project-specific guidelines and motivations. Hadley Wickham's Books [Advanced R](http://adv-r.had.co.nz/) and [Package Development](http://r-pkgs.had.co.nz/) are canonical, free, online references.

* [[Coding Style]]
* [[Documentation|Roxygen2]]
* [[Testing]]
* [[Package Data]]
* [[Logging, Warnings, and Error Messages | Logging]]