# Using Git


This document describes the steps required to download PEcAn, make changes to code, and submit your changes using Git in Conjunction with Github.

Git is a version control software; GitHub is a project-hosting website that is similar to [Redmine](https://ebi-forecast.igb.illinois.edu/redmine/) but easier to use for open and collaborative development.

Git is a free & open source, distributed version control system designed to handle everything from small to very large projects with speed and efficiency. Every Git clone is a full-fledged repository with complete history and full revision tracking capabilities, not dependent on network access or a central server. Branching and merging are fast and easy to do.


**If you are new to Git:**

    Familiarize yourself with Git and Github
    
        - Github: [5 minute illustrated tutorial](https://guides.github.com/introduction/flow/). 
        - Git:[Learn Git](https://www.codecademy.com/learn/learn-git) is a great web-based interactive tutorial.
              [LearnGitBranching](http://pcottle.github.com/learnGitBranching/)
              [TryGit](http://try.github.com)
          
**If you would like to make changes:**
    
    1. Start with the one-time set-up instructions under [Before any work is done](#before-any-work-is-done). 
    
    2. Check out our existing issues and see if someone is already working on your proposed changes.
    
        - To ask questions, report bugs, and/or request features, see our documentation for [reporting issues on GitHub][Overview]    
        
    3. To make changes to PEcAn code:
        
        - follow our ["Basic workflow"](#basic-workflow) if you plan on making small, one time or infrequent changes to PEcAn.
        
        - follow our ["Quick and Easy"](#quick-and-easy-workflow) if you are a PEcAn Project member and you would like to make a quick, small change.
          
        - follow our ["Suggested Workflow"](#suggested-workflow) if you plan on making sustained contributions to PEcAn.
    
        
    
    
**Using GitHub** 
The easiest way to get working with GitHub is by installing the GitHub
client. For instructions for your specific OS and download of the
GitHub client, see https://help.github.com/articles/set-up-git.
This will help you set up an SSH key to push code back to GitHub. To
check out a project you do not need to have an ssh key and you can use
the https or git url to check out the code.

**URLs** In the rest of the document will use specific URL’s to clone the code.
There a few URL’s you can use to clone a project, using https, ssh and
git. You can use either https or git to clone a repository and write to
it. The git protocol is read-only. More information can be found [here](https://help.github.com/articles/which-remote-url-should-i-use/)

### PEcAnProject on GitHub

**[PEcAn source code](https://github.com/PecanProject/pecan.git)**
 
**[BETYdb source code](https://github.com/PecanProject/bety.git)**
 

## Recommended Git Workflow


**Each feature should be in it’s own branch** (for example each github
issue is a branch, names of branches are often the issue in a bug
tracking system).

**Commit and Push Frequency** On your branch, commit **_at minimum once a day before you push changes:_** even better: every time you reach a stopping point and move to a new issue. best: any time that you have done work that you do not want to re-do. Remember, pushing changes to your branch is like saving a draft. Submit a pull request when you are done.


### Before any work is done:

The first step below only needs to be done once when you first start working on the PEcAn code. The steps below that need to be done to set up PEcAn on your computer, and would need to be repeated if you move to a new computer. If you are working from the PEcAn VM, you can skip the "git clone" since the PEcAn code is already installed. 

Most people will not be able to work in the PEcAn repository directly and will need to create a fork of the PEcAn source code in their own folder. To fork PEcAn into your own github space ([github help: "fork a repo"](https://help.github.com/articles/fork-a-repo)). This forked repository will allow you to create branches and commit changes back to GitHub and create pull requests to the master of PEcAn.

The forked repository is the only way for external people to commit code back to PEcAn and BETY. The pull request will start a review process that will eventually result in the code being merged into the main copy of the codebase. See https://help.github.com/articles/fork-a-repo for more information,  especially on how to keep your fork up to date with respect to the original. (Rstudio users should also see [Git + Rstudio](Using-Git.md#git--rstudio), below)

You can setup SSH keys to make it easier to commit cod back to GitHub. This might especially be true if you are working from a cluster, see [set up ssh keys](https://help.github.com/articles/generating-ssh-keys)

1. Introduce yourself to GIT

        `git config --global user.name "FULLNAME"`
        `git config --global user.email you@yourdomain.example.com`

2. Fork PEcAn on GitHub. Goto the PEcAn source code and click on the Fork button in the upper right. This will create a copy of PEcAn in your personal space.

3. Clone to your local machine 

        `git clone git@github.com:<username>/pecan.git`

3. Define upstream repository
 
        `cd pecan`
        `git remote add upstream git@github.com:PecanProject/pecan.git`
        
4. Read [this article](http://nvie.com/posts/a-successful-git-branching-model/) about how we manage development branches.

### Github Organization: Milestones, Issues, Tasks

When making changes it is important to let others in the community know what changes you will be making. To do this, open a github issue to describe what cahnges you will be making and why you are making them. Milestones, issues, and tasks can be used to organize specific features or research projects. In general, there is a heirarchy:

* Milestones (Big picture): contains many issues and organizes what is due for the next release.(Time Sensitive)
* Epic Issues ("Story"): Describes a larger feature that may contain many other smaller tasks and issues.(Not Time Sensitive)
* Issues (Specific features / bugs): may contain a list of tasks; represents focused issue and can be part of a larger set of issues under an "Epic" issue.
* Task list (to do list, "Tasks"): list of steps required to close an issue, e.g.:

```
 * [ ] first do this
 * [ ] then this
 * [ ] completed when x and y
```

### Basic Workflow
1. Move to "develop" branch 

    `git checkout develop`

2. Pull latest code from "develop" branch git pull

    `git pull`
    
3. Make your Changes and stage them

    `git add file_you_changed.R`
    
4. Commit! (Do this often. Even when you are not done with changes)

    `git commit -m "describe your changes"`
  
5. Push your commits to branch you're working on 

    `git push origin develop`

6. Submit pull request.
    
    Use [Github web interface to open pull request](https://help.github.com/articles/creating-a-pull-request/). Make sure you are comparing base branch "develop" to your branch.

### Quick and Easy Workflow
**NOTE: ** Only Applicalble if you are a member of the PEcAn Project on Github)

-The "easiest"" approach is to use GitHub's browser based workflow. This is useful when your change is a few lines, if you are editing a wiki, or if the edit is trivial (and won't break the code). The [GitHub documentation is here](https://help.github.com/articles/github-flow-in-the-browser) but it is simple: find the page or file you want to edit, click "edit" and then the GitHub web application will automatically create a branch with your changes and then you can submit a pull request.

### Suggested Workflow
        
1. Move to "develop" branch 

    `git checkout develop`

2. Pull latest code from "develop" branch git pull

    `git pull`
    
3. Create branch specific to issue/feature you are working on 

    `git checkout -b <issuenumber>-description`
    
4. Make your Changes and stage them

    `git add file_you_changed.R`
    
5. Commit! (Do this often. Even when you are not done with changes)

    `git commit -m "describe your changes"`
  
6. Push your commits to branch you're working on 

    `git push origin <issuenumber>-description`
   
7.  Run any tests / make sure that code compiles


    * For PEcAn: Build most recent versions of R packages 

        Run `make` while in `pecan` directory. More information about `make` in PEcAn can be found [here][Updating PEcAN Code and Bety Database]

    * For BETYdb ([see BETY wiki](https://github.com/PecanProject/bety/wiki/Testing#running-the-tests))

        `rspec`

8. Push this branch to your github space 

    git push origin <branchname>

9. Submit pull request.
    
    Use [Github web interface to open pull request](https://help.github.com/articles/creating-a-pull-request/). Make sure you are comparing base branch "develop" to your branch.


**After pull request is merged and you would like to delete branch**

1. Make sure you start in develop

        git checkout develop

2. delete branch remotely 

        git push origin --delete <branchname>

3. delete branch locally 

        git branch -D <branchname>


### Link commits to issues

You can reference and close issues from comments, pull requests, and commit messages. This should be done when you commit code that is related to or will close/fix an existing issue. 

There are two ways to do this. One easy way is to include the following text in your commit message:

* [**Github**](https://github.com/blog/1386-closing-issues-via-commit-messages)
  * to close: "closes gh-xxx" (or syn. close, closed, fixes, fix, fixed)  
  * to reference: just the issue number (e.g. "gh-xxx")
  * avoid "closes #xxx" which will cross-reference Redmine issues 



### Other Useful Git Commands:


If during above process you want to work on something else, commit all
your code, create a new branch, and work on new branch. 


* Delete a branch 

    `git branch -d <name of branch>`

* To push a branch git: 

    `git push -u origin `<name of branch>`
  
* To check out a branch: 
  

    `git fetch origin`
    `git checkout --track origin/<name of branch>`
  

* Show graph of commits:

    `git log --graph --oneline --all`

### Tags

Git supports two types of tags: lightweight and annotated. For more information see the [Tagging Chapter in the Git documentation](http://git-scm.com/book/ch2-6.html).

Lightweight tags are useful, but here we discuss the annotated tags that are used for marking stable versions, major releases, and versions associated with published results. 

The basic command is `git tag`. The `-a` flag means 'annotated' and `-m` is used before a message.  Here is an example:

    `git tag -a v0.6 -m "stable version with foo and bar features, used in the foobar publication by Bob"`

Adding a tag to the a remote repository must be done explicitly with a push, e.g.

    `git push v0.6`
    
To use a tagged version, just checkout: 

    `git checkout v0.6`
    
To tag an earlier commit, just append the commit SHA to the command, e.g. 

    `git tag -a v0.99 -m "last version before 1.0" 9fceb02`


## Git + Rstudio


Rstudio is nicely integrated with many development tools, including git and GitHub. 
It is quite easy to check out source code from within the Rstudio program or browser.
The Rstudio documentation includes useful overviews of [version control](http://www.rstudio.com/ide/docs/version_control/overview) and [R package development](http://www.rstudio.com/ide/docs/packages/overview). 

Once you have git installed on your computer (see the [Rstudio version control](http://www.rstudio.com/ide/docs/version_control/overview) documentation for instructions), you can use the following steps to install the PEcAn source code in Rstudio.

### Creating a Read-only version:

This is a fast way to clone the repository that does not support contributing new changes (this can be done with further modification). 

1.  install Rstudio (www.rstudio.com)
2.  click (upper right) project
 *   create project
 *   version control
 *   Git - clone a project from a Git Repository
 *   paste https://www.github.com/PecanProject/pecan
 *   choose working dir. for repo

## For development:

1.  create account on github
2.  create a fork of the PEcAn repository to your own account https://www.github.com/pecanproject/pecan
3.  install Rstudio (www.rstudio.com)
4. generate an ssh key 
 * in Rstudio: 
  * `Tools -> Options -> Git/SVN -> "create RSA key"`
  * `View public key -> ctrl+C to copy`
 * in GitHub
  * go to [ssh settings](https://github.com/settings/ssh)
  * `-> 'add ssh key' -> ctrl+V to paste -> 'add key'` 
2. Create project in Rstudio
 *  `project (upper right) -> create project -> version control -> Git - clone a project from a Git Repository`
 * paste repository url `git@github.com:<username>/pecan.git>`
 * choose working dir. for repository

References:
-----------


#### Git Documentation

* Scott Chacon, ‘Pro Git book’,
[http://git-scm.com/book](http://git-scm.com/book)
* GitHub help pages,
[https://help.github.com](https://help.github.com)/
* Main GIT page,
[http://git-scm.com/documentation](http://git-scm.com/documentation)
* Information about branches,
[http://nvie.com/posts/a-successful-git-branching-model](http://nvie.com/posts/a-successful-git-branching-model)/
* [Stackoverflow highest voted questions tagged "git"](http://stackoverflow.com/questions/tagged/git?sort=votes&pagesize=50)


#### GitHub Documentation

When in doubt, the first step is to click the "Help" button at the top of the page.

* [GitHub Flow](http://scottchacon.com/2011/08/31/github-flow.html) by
Scott Chacon (Git evangelist and Ruby developer working on GitHub.com)
* [GitHub FAQ](https://help.github.com/)
* [Using Pull Requests](https://help.github.com/articles/using-pull-requests)
* [SSH Keys](https://help.github.com/articles/generating-ssh-keys)