#' @title Substitute single value into ED2IN
#' 
#' @author Alexey Shiklomanov
#' @description Given a tag, find that tag in the provided ED2IN character 
#' vector and change its value. If the tag is not found, do nothing.
#' 
#' @param tag ED2IN tag, e.g. "SFILIN"
#' @param value Value for setting the tag
#' @param ed2in Character vector containing ED2IN file, usually generated by 
#' \code{readLines}.
#' 
#' @export
ed2in_set_value <- function(tag, value, ed2in, 
                            modstring = "Modified by PEcAn") {
    if (grepl("NL%", tag)) {
      PEcAn.logger::logger.warn("NL% is automatically prepended ",
                               "to tags. Removing it from provided tag.")
      tag <- gsub('NL%', '', tag)
    }
    tag <- toupper(tag)
    regex <- sprintf("(^[[:blank:]]*NL%%%s)[[:blank:]]+=.*", tag)
    in_ed2in <- any(grepl(regex, ed2in))
    if (!in_ed2in) {
      PEcAn.logger::logger.warn("Tag ", shQuote(tag), " not found in ED2IN. ")
      return(ed2in)
    }

    # If value is a string, escape it with quotes
    numval <- suppressWarnings(as.numeric(value))
    if (is.na(numval)) {
        value <- shQuote(value)
    }

    ed2in_out <- gsub(regex, paste0("\\1 = ", value, "    !! ", modstring),
                      ed2in)
    return(ed2in_out)
}

#' @title Substitute list of tag-value pairs into ED2IN
#' 
#' @author Alexey Shiklomanov
#' @param tag_val_list Named list of tag-value pairs. List names should match 
#' ed2in tags.
#' @param ... Other parameters to \code{ed2in_set_value}
#' @inheritParams ed2in_set_value
#' @export
ed2in_set_value_list <- function(tag_val_list, ed2in, ...) {
  ed2in_out <- ed2in
  for (tag in names(tag_val_list)) {
    ed2in_out <- ed2in_set_value(tag = tag,
                                 value = tag_val_list[[tag]],
                                 ed2in = ed2in_out,
                                 ...)
  }
  return(ed2in_out)
}

