#' @title Get ED history restart file path
#'
#' @author Alexey Shiklomanov
#' @param mod_outdir Directory where PEcAn stores ensemble outputs. Usually 
#' \code{<workflowID>/out}
#' @param runid PEcAn run ID
#' @param file.time Start or end time from SDA analysis
get_restartfile.ED2 <- function(mod_outdir, runid, file.time) {
    runid <- as.character(runid)
    histfile_path <- file.path(mod_outdir, runid)

    file_year <- lubridate::year(file.time)
    file_month <- lubridate::month(file.time)
    file_day <- lubridate::day(file.time)
    datetime_string <- sprintf("%04d-%02d-%02d-000000", 
                               file_year, 
                               file_month,
                               file_day)
    histfile_string <- paste0("history-S-",
                              datetime_string,
                              ".*\\.h5$")

    histfile <- list.files(histfile_path, 
                           histfile_string, 
                           full.names = TRUE)
    if (length(histfile) > 1) {
        PEcAn.utils::logger.error("Multiple history files found.")
        return(NULL)
    } else if (length(histfile) < 1) {
        PEcAn.utils::logger.error("No history files found.")
        return(NULL)
    } else {
        PEcAn.utils::logger.info("Using history file: ",
                                  histfile)
        return(histfile)
    }
}

#' @title Get ED2 config.xml file
#'
#' @author Alexey Shiklomanov
#' @param rundir Model run directory. Usually \code{<workflowID>/run}
#' @inheritParams get_restartfile.ED2
get_configxml.ED2 <- function(rundir, runid) {
    runid <- as.character(runid)
    confxml_path <- file.path(rundir, runid, "config.xml")
    confxml <- XML::xmlToList(XML::xmlParse(confxml_path))
    return(confxml)
}

#' @title Generate ED2 cohort to patch mapping vector
#' 
#' @author Alexey Shiklomanov
#' @description Generate a vector of integer indices for mapping ED state 
#' cohort vectors onto patches, for instance for use with \code{tapply}.
#' @param nc \code{ncdf4} object for ED history restart file.
patch_cohort_index <- function(nc) {
    # Patch length
    paco_N <- ncdf4::ncvar_get(nc, "PACO_N")
    patch_index <- do.call(c, mapply(rep, seq_along(paco_N), paco_N))
    return(patch_index)
}

#' @title Substitute values into ED2IN
#' 
#' @author Alexey Shiklomanov
#' @param tag ED2IN tag, e.g. "NL%SFILIN"
#' @param value Value for setting the tag
#' @param ed2in Character vector containing ED2IN file, usually generated by 
#' \code{readLines}.
ed2in_sub <- function(tag, value, ed2in) {
    regex <- sprintf("(^[[:blank:]]*%s)[[:blank:]]+=.*", tag)
    # If value is a string, escape it with quotes
    numval <- as.numeric(value)
    if (is.na(numval)) {
        value <- shQuote(value)
    }

    ed2in_out <- gsub(regex, paste0("\\1 = ", value, 
                                    "   !! Modified by write.restart.ED2"),
                      ed2in)
    return(ed2in_out)
}

#' @title List only files in a directory
#' 
#' @author Alexey Shiklomanov
#' @inheritParams base::list.files
list.files.nodir <- function(path, ...) {
    allfiles <- list.files(path, ...)
    dirs <- list.dirs(path, ...)
    outfiles <- setdiff(allfiles, dirs)
    return(outfiles)
}
