spp.cleanup<-function(data){

data$Spp[data$Spp=="ABBA"]<-"ABBA"
data$Spp[data$Spp=="ACPE"]<-"ACPE"
data$Spp[data$Spp=="ACRU"]<-"ACRU"
data$Spp[data$Spp=="ACSA"]<-"ACSA3"
  data$Spp[data$Spp=="ACSA4"]<-"ACSA3"
  data$Spp[data$Spp=="ACSA5"]<-"ACSA3"
  data$Spp[data$Spp=="ACSA6"]<-"ACSA3"
  data$Spp[data$Spp=="acsa"]<-"ACSA3"
  data$Spp[data$Spp=="ASCA3"]<-"ACSA3"
data$Spp[data$Spp=="ACSP"]<-"ACSP2"
  data$Spp[data$Spp=="ACSP2"]<-"ACSP2"
data$Spp[data$Spp=="BEAL2"]<-"BEAL2"
  data$Spp[data$Spp=="BEAL"]<-"BEAL2"
  data$Spp[data$Spp=="BEAL2"]<-"BEAL2"
  data$Spp[data$Spp=="BRAL2"]<-"BEAL2"
data$Spp[data$Spp=="BELE"]<-"BELE"
  data$Spp[data$Spp=="BELI"]<-"BELE"
data$Spp[data$Spp=="BEPA"]<-"BEPA"
data$Spp[data$Spp=="FAGR"]<-"FAGR"
data$Spp[data$Spp=="FRAM2"]<-"FRAM2"
  data$Spp[data$Spp=="FRAM"]<-"FRAM2"
data$Spp[data$Spp=="FRNI"]<-"FRNI"
data$Spp[data$Spp=="FRPE"]<-"FRPE"
data$Spp[data$Spp=="HAVI4"]<-"HAVI4"
  data$Spp[data$Spp=="HAVI"]<-"HAVI4"
data$Spp[data$Spp=="OSVI"]<-"OSVI"
data$Spp[data$Spp=="PIGL"]<-"PIGL"
data$Spp[data$Spp=="PIMA"]<-"PIMA"
  data$Spp[data$Spp=="PIAM"]<-"PIMA"
data$Spp[data$Spp=="PIRU"]<-"PIRU"
data$Spp[data$Spp=="PIRE"]<-"PIRE"
  data$Spp[data$Spp=="PIER"]<-"PIRE"
data$Spp[data$Spp=="PIST"]<-"PIST"
  data$Spp[data$Spp=="PSIT"]<-"PIST"
data$Spp[data$Spp=="POGR4"]<-"POGR4"
  data$Spp[data$Spp=="POGR"]<-"POGR4"
data$Spp[data$Spp=="POTR5"]<-"POTR5"
  data$Spp[data$Spp=="POTR"]<-"POTR5"
data$Spp[data$Spp=="PRPE2"]<-"PRPE2"
  data$Spp[data$Spp=="PRPE"]<-"PRPE2"
data$Spp[data$Spp=="PRSE2"]<-"PRSE2"
  data$Spp[data$Spp=="PRSE"]<-"PRSE2"
data$Spp[data$Spp=="QURU"]<-"QURU"
data$Spp[data$Spp=="THOC2"]<-"THOC2"
data$Spp[data$Spp=="THOC"]<-"THOC2"
data$Spp[data$Spp=="TIAM"]<-"TIAM"
  data$Spp[data$Spp=="TIMA"]<-"TIAM"
data$Spp[data$Spp=="TSCA"]<-"TSCA"
data$Spp[data$Spp=="ULAM"]<-"ULAM"

data$Spp[data$Spp=="Missing Data"]<-"Missing_Data"
data$Spp[data$Spp=="MissingData"]<-"Missing_Data"
data$Spp[data$Spp=="UN"]<-"Missing_Data"
data$Spp[data$Spp=="un"]<-"Missing_Data"
data$Spp[grep("\\?",data$Spp)]<-"Missing_Data"
data$Spp[grep(" Spp",data$Spp)]<-"Missing_Data"
data$Spp[grep(" SPP",data$Spp)]<-"Missing_Data"
data$Spp[grep(" spp",data$Spp)]<-"Missing_Data"
data$Spp[data$Spp==""]<-"Missing_Data"

return(data$Spp)
}
