## Scenario Generation for RCMEM

```{r libraries}
library(data.water)
library(tidyverse)
```


### Run Some Queries

``` {r run queries}

gauge_path <- system.file("extdata",
                          "noaa_us_gauge_info.csv",
                          package = "data.water")

# 4. Query future SLR
gauge_tab <- readr::read_csv(gauge_path, show_col_types = FALSE) %>% 
  filter(noaa_id %in% c(c(9410170, 9410660, 9414290))) %>% 
  rename(gauge_id = noaa_id)

scenario_output <- data.water::generateFullTidalScenario(
   station_id = c(9410170, 9410660, 9414290),
   run_hindcast = T,
   run_forecast = T,
   hindcast_start = lubridate::ymd(gauge_tab$startDate),
   forecast_start = 2024,
   forecast_end = 2100,
   scenario = c("ssp126", "ssp245", "ssp370"),
   target_quantile = c(0.25, 0.5, 0.75),
   include_lt_tidal_const = T,
   datum_start_year = 1980,
   datum_end_year = 2025)

```

## Add files into one and visualize
```{r compile data}

all_scenario_info <- scenario_output[[1]] %>% 
  distinct(gauge_id, scenario_name, confidence, quantile)

MSL_list <- list()
amp_list <- list()

MHW_names <- c("HHA", "HHS", "HH", "LH")
MLW_names <- c("LLA", "LLS", "LL", "HL")
common_names = c("annual", "spring", "daily larger", "daily smaller")

for (i in 1:nrow(all_scenario_info)) {
  
  temp_scenario_info <- all_scenario_info[i,]
  # 
  MSL_temp <- scenario_output[[1]] %>% 
    semi_join(temp_scenario_info)
  
  temp_MHW <- MSL_temp %>% 
    select(gauge_id, scenario_name,confidence,quantile, MHW_names)
  
 #  names(temp_MHW) <- MHW_names
  
  temp_MHW <- temp_MHW %>% 
    mutate(year = MSL_temp$year) %>% 
    pivot_longer(names_to = "flood level",
                 values_to = "higher_flood",
                 -c(year,gauge_id, scenario_name,confidence,quantile)) %>% 
     mutate(`flood level` = recode(`flood level`, 
                                "HHA" =  "annual",
                                "HHS" = "spring", 
                                "HH" = "daily larger", 
                                "LH"= "daily smaller"))
  
  temp_MLW <- MSL_temp %>% 
    select(gauge_id, scenario_name,confidence,quantile,MLW_names)
  
  # names(temp_MLW) <- MLW_names
  
  temp_MLW <- temp_MLW %>% 
    mutate(year = MSL_temp$year) %>% 
    pivot_longer(names_to = "flood level",
                 values_to = "lower_flood",
                 -c(year, gauge_id, scenario_name,confidence,quantile)) %>% 
    mutate(`flood level` = recode(`flood level`, 
                                "LLA" =  "annual",
                                "LLS" = "spring", 
                                "LL" = "daily larger", 
                                "HL"= "daily smaller"))
  
  amp_comp <- temp_MHW %>% 
    left_join(temp_MLW)
  
  amp_list[[i]] <- amp_comp
  MSL_list[[i]] <- MSL_temp
  
}

MSL_vis <- bind_rows(MSL_list)
amp_vis <- bind_rows(amp_list)


MSL_vis <- MSL_vis %>% 
  left_join(gauge_tab)
amp_vis <- amp_vis %>% 
  left_join(gauge_tab)


ggplot(MSL_vis %>% filter(quantile == 0.5,
                          scenario_name == "ssp245")) +
    geom_ribbon(data=amp_vis %>% filter(quantile == 0.5,
                                        scenario_name == "ssp245"), aes(x = year,
                           ymin = lower_flood, 
                           ymax = higher_flood,
                           group = `flood level`,
                           col = `flood level`), 
              # alpha = 0.5, 
              fill = NA) +
  geom_line(aes(x = year, y = meanSeaLevel)) +
  # geom_point(aes(x = year, y = meanSeaLevel)) +
  facet_wrap(noaa_name~scenario_name) +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  # ggtitle("Los Angeles - Flooding Scenarios by RCP and probability") +
  ylab("Water Level (cm; NAVD88)")


ggplot(MSL_vis) +
    # geom_ribbon(data=amp_vis, aes(x = year,
    #                        ymin = lower_flood, 
    #                        ymax = higher_flood,
    #                        group = `flood level`,
    #                        col = `flood level`), 
    #           # alpha = 0.5, 
    #           fill = NA) +
  geom_line(aes(x = year, y = meanSeaLevel, color = scenario_name, lty = as.character(quantile))) +
  # geom_point(aes(x = year, y = meanSeaLevel)) +
  facet_grid(.~noaa_name) +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  # ggtitle("Los Angeles - Flooding Scenarios by RCP and probability") +
  ylab("Water Level (cm; NAVD88)")


ggplot(MSL_vis) +
    # geom_ribbon(data=amp_vis, aes(x = year,
    #                        ymin = lower_flood, 
    #                        ymax = higher_flood,
    #                        group = `flood level`,
    #                        col = `flood level`), 
    #           # alpha = 0.5, 
    #           fill = NA) +
  geom_line(aes(x = year, y = meanSeaLevel, color = noaa_name)) +
  # geom_point(aes(x = year, y = meanSeaLevel)) +
  facet_grid(scenario_name~ as.character(quantile)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  # ggtitle("Los Angeles - Flooding Scenarios by RCP and probability") +
  ylab("Water Level (cm; NAVD88)")




```


```{r check out nearest noaa gauge}


sites <- data.frame(
  site = c("Tijuana", "Seal Beach", "Triangle"), 
  latitude = c(32.57427143, 33.73520729, 37.45842503),	
  longitude = c(-117.1287429, -118.0792275, -121.9773209)
)

sites_w_gauges <- data.water::findNearestNoaaGauge(sites)
(sites_w_gauges)

```

