#!/bin/bash

# redirect output
exec 3>&1
exec &> "@OUTDIR@/logfile.txt"

# host specific setup
@HOST_SETUP@

# cdo setup
@CDO_SETUP@

# create output folder
mkdir -p "@OUTDIR@"

# Convert any relative paths to absolute
# (otherwise we'd lose track of them when cd'ing into rundir)
OUTDIR=$(cd "@OUTDIR@" && pwd -P)
RUNDIR=$(cd "@RUNDIR@" && pwd -P)
SITE_MET=$(cd $(dirname "@SITE_MET@") && pwd -P)/$(basename "@SITE_MET@")
BINARY=$(cd $(dirname "@BINARY@") && pwd -P)/$(basename "@BINARY@")

# see if application needs running
if [ ! -e "${OUTDIR}/sipnet.out" ]; then
  cd "$RUNDIR"
  ln -s "${SITE_MET}" sipnet.clim

  "${BINARY}"
  STATUS=$?
  
  # copy output
  mv "${RUNDIR}/sipnet.out" "$OUTDIR"

  # check the status
  if [ $STATUS -ne 0 ]; then
    echo -e "ERROR IN MODEL RUN\nLogfile is located at '${OUTDIR}/logfile.txt'" >&3
    exit $STATUS
  fi

  # conversion to MsTMIP not done in this single-segment step.
  # The whole-job script will handle conversion after all segments have run.
fi

# copy readme with specs to output
cp  "${RUNDIR}/README.txt" "${OUTDIR}/README.txt"

# run getdata to extract right variables

# host specific teardown
@HOST_TEARDOWN@

# all done
echo -e "MODEL FINISHED\nLogfile is located at '${OUTDIR}/logfile.txt'" >&3
