# Testing with the `testthat` package {#appendix-testthat}

Tests are found in `<package>/tests/testthat/` (for example, `base/utils/inst/tests/`)

See attached file and
[http://r-pkgs.had.co.nz/tests.html](http://r-pkgs.had.co.nz/tests.html)
for details on how to use the testthat package.

## List of Expectations

|Full	|Abbreviation|
|---|----|
|expect_that(x, is_true())	|expect_true(x)|
|expect_that(x, is_false())	|expect_false(x)|
|expect_that(x, is_a(y))	|expect_is(x, y)|
|expect_that(x, equals(y))	|expect_equal(x, y)|
|expect_that(x, is_equivalent_to(y))	|expect_equivalent(x, y)|
|expect_that(x, is_identical_to(y))	|expect_identical(x, y)|
|expect_that(x, matches(y))	|expect_matches(x, y)|
|expect_that(x, prints_text(y))	|expect_output(x, y)|
|expect_that(x, shows_message(y))	|expect_message(x, y)|
|expect_that(x, gives_warning(y))	|expect_warning(x, y)|
|expect_that(x, throws_error(y))	|expect_error(x, y)|

## Basic use of the `testthat` package

Create a file called `<packagename>/tests/testthat.R` with the following contents:

```r
library(testthat)
library(mypackage)

test_check("mypackage")
```

Tests should be placed in `<packagename>/tests/testthat/test-<sourcefilename>.R`, and look like the following:

```r
test_that("mathematical operators plus and minus work as expected",{
  expect_equal(sum(1,1), 2)
  expect_equal(sum(-1,-1), -2)
  expect_equal(sum(1,NA), NA)
  expect_error(sum("cat"))
  set.seed(0)
  expect_equal(sum(matrix(1:100)), sum(data.frame(1:100)))
})

test_that("different testing functions work, giving excuse to demonstrate",{
  expect_identical(1, 1)
  expect_identical(numeric(1), integer(1))
  expect_equivalent(numeric(1), integer(1))
  expect_warning(mean('1'))
  expect_that(mean('1'), gives_warning("argument is not numeric or logical: returning NA"))
  expect_warning(mean('1'), "argument is not numeric or logical: returning NA")
  expect_message(message("a"), "a")
})
```

## Data for tests

Many of PEcAn’s functions require inputs that are provided as data.
These can be in the `data` or the `inst/extdata` folders of a package.
Data that are not package specific should be placed in the `PEcAn.all` (`base/all`) or
`PEcAn.utils` (`base/utils`) packages.

Some useful conventions:

## Settings

* A generic settings can be found in the `PEcAn.all` package
```r
settings.xml <- system.file("pecan.biocro.xml", package = "PEcAn.BIOCRO")
settings <- read.settings(settings.xml)
```

*  database settings can be specified, and tests run only if a connection is available

We currently use the following database to run tests against; tests that require access to a database should check `db.exists()` and be skipped if it returns FALSE to avoid failed tests on systems that do not have the database installed.

```r
settings$database <- list(userid = "bety", 
                          passwd = "bety", 
                          name = "bety",     # database name 
                          host = "localhost" # server name)
test_that(..., {
  skip_if_not(db.exists(settings$database))
  ## write tests here
})
```

*  instructions for installing this are available on the [VM creation
    wiki](VM-Creation.md)
*  examples can be found in the PEcAn.DB package (`base/db/tests/testthat/`).

* Model specific settings can go in the model-specific module, for
example:

```r
settings.xml <- system.file("extdata/pecan.biocro.xml", package = "PEcAn.BIOCRO")
settings <- read.settings(settings.xml)
```
* test-specific settings:
  - settings text can be specified inline:
    ```
    settings.text <- "
      <pecan>
        <nocheck>nope</nocheck> ## allows bypass of checks in the read.settings functions
        <pfts>
          <pft>
            <name>ebifarm.pavi</name>
            <outdir>test/</outdir>
          </pft>
        </pfts>
        <outdir>test/</outdir>
        <database>
          <userid>bety</userid>
          <passwd>bety</passwd>
          <location>localhost</location>
          <name>bety</name>
        </database>
      </pecan>"
    settings <- read.settings(settings.text)
    ```
  - values in settings can be updated:
    ```r
    settings <- read.settings(settings.text)
    settings$outdir <- "/tmp" ## or any other settings
    ```

## Helper functions for unit tests

*  `PEcAn.utils::tryl` returns `FALSE` if function gives error
*  `PEcAn.utils::temp.settings` creates temporary settings file
*  `PEcAn.DB::db.exists` returns `TRUE` if connection to database is available
