### ED Configuration

ED2 is configured using 2 files which are placed in the run folder.

* **ED2IN** : template for this file is located at models/ed/inst/ED2IN.\<revision\>. The values in this template that need to be modified are described below and are surrounded with @ symbols.
* **config.xml** : this file is generated by PEcAn. Some values are stored in the pecan.xml in \<pfts\>\<pft\>\<constants\> section as well as in \<model\> section.

An example of the template can be found in [ED2IN.r82](https://github.com/PecanProject/pecan/blob/master/models/ed/inst/ED2IN.r82)

## ED2IN configuration variables

**@ENSNAME@** : run id of the simulation, used in template for NL%EXPNME

**@START_MONTH@** : start of simulation UTC time, from \<run\>\<start.date\>, used in template for NL%IMONTHA  
**@START_DAY@** : start of simulation UTC time, from \<run\>\<start.date\>, used in template for NL%IDATEA  
**@START_YEAR@** : start of simulation UTC time, from \<run\>\<start.date\>, used in template for NL%IYEARA  
**@END_MONTH@** : end of simulation UTC time, from \<run\>\<end.date\>, used in template for NL%IMONTHZ  
**@END_DAY@** : end of simulation UTC time, from \<run\>\<end.date\>, used in template for NL%IDATEZ  
**@END_YEAR@** : end of simulation UTC time, from \<run\>\<end.date\>, used in template for NL%IYEARZ  

**@SITE_LAT@** : site latitude location, from \<run\>\<site\>\<lat\>, used in template for NL%POI_LAT  
**@SITE_LON@** : site longitude location, from \<run\>\<site\>\<lon\>, used in template for NL%POI_LON  

**@SITE_MET@** : met header location, from \<run\>\<site\>\<met\>, used in template for NL%ED_MET_DRIVER_DB  
**@MET_START@** : first year of met data, from \<run\>\<site\>\<met.start\>, used in template for NL%METCYC1  
**@MET_END@** : last year of met data, from \<run\>\<site\>\<met.end\>, used in template for NL%METCYCF  

**@PHENOL_SCHEME@** : phenology scheme, if this variabe is 1 the following 3 fields will be used, otherwise they will be set to empty strings, from \<model\>\<phenol.scheme\>, used in template for NL%IPHEN_SCHEME  
**@PHENOL_START@** : first year for phenology, from \<model\>\<phenol.start\>, used in template for NL%IPHENYS1 and NL%IPHENYF1  
**@PHENOL_END@** : last year for phenology, from \<model\>\<phenol.end\>, used in template for NL%IPHENYSF and NL%IPHENYFF  
**@PHENOL@** : path and prefix of the prescribed phenology data, from \<model\>\<phenol\>, used in template for NL%PHENPATH  

**@SITE_PSSCSS@** :  path and prefix of the previous ecosystem state, from \<model\>\<psscss\>, used in template for NL%SFILIN  
**@ED_VEG@** : path and prefix of the vegetation database, used only to determine the land/water mask, from \<model\>\<veg\>, used in template for NL%VEG_DATABASE  
**@ED_SOIL@** : path and prefix of the soil database, used to determine the soil type, from \<model\>\<soil\>, used in template for NL%SOIL_DATABASE  
**@ED_INPUTS@** : input directory with dataset to initialise chilling degrees and growing degree days, which is used to drive the cold-deciduous phenology, from \<model\>\<inputs\>, used in template for NL%THSUMS_DATABASE  

**@FFILOUT@** : path and prefix for analysis files, generated from \<run\>\<host\>\<outdir\>/run.id/analysis,  used in template for NL%FFILOUT  
**@SFILOUT@** : path and prefix for history files, generated from \<run\>\<host\>\<outdir\>/run.id/history,  used in template for NL%SFILOUT  

**@CONFIGFILE@** : XML file containing additional parameter settings, this is always "config.xml", used in template for NL%IEDCNFGF  

**@OUTDIR@** :  location where output files are written (**without the runid**), from \<run\>\<host\>\<outdir\>, should not be used.  
**@SCRATCH@** : local scratch space for outputs, generated /scratch/\<username\>/run$scratch, should not be used right now since it only works on ebi-cluster  

**ED Computation HPC**

**TACC lonestar**

```bash
module load hdf5
curl -o ED.r82.tgz http://isda.ncsa.illinois.edu/~kooper/EBI/ED.r82.tgz
tar zxf ED.r82.tgz
rm ED.r82.tgz
cd ED.r82/ED/build/bin
curl -o include.mk.lonestar http://isda.ncsa.illinois.edu/~kooper/EBI/include.mk.lonestar
make OPT=lonestar
```

**TACC stampede**

```bash
module load hdf5
curl -o ED.r82.tgz http://isda.ncsa.illinois.edu/~kooper/EBI/ED.r82.tgz
tar zxf ED.r82.tgz
rm ED.r82.tgz
cd ED.r82/ED/build/bin
curl -o include.mk.stampede http://isda.ncsa.illinois.edu/~kooper/EBI/include.mk.stampede
make OPT=stampede
```
