#!/usr/bin/env Rscript
# autogenerated do not edit
# use scripts/generate_dependencies.R

# Don't use X11 for rgl
Sys.setenv(RGL_USE_NULL = TRUE)
rlib <- Sys.getenv('R_LIBS_USER', '/usr/local/lib/R/site-library')
Sys.setenv(RLIB = rlib)

# install remotes first in case packages are references in dependencies
remotes::install_github(c(
'adokter/suntools',
'araiho/linkages_package',
'chuhousen/amerifluxr',
'ebimodeling/biocro@0.951',
'MikkoPeltoniemi/Rpreles',
'ropensci/geonames',
'ropensci/nneo'
), lib = rlib)

# install package listed as Depends, Imports, Suggests of any PEcAn package
#   that do not have a stated version limit
wanted <- c(
'amerifluxr',
'arrow',
'assertthat',
'BayesianTools',
'BioCro',
'bit64',
'BrownDog',
'corrplot',
'curl',
'data.table',
'dataone',
'datapack',
'DBI',
'dbplyr',
'devtools',
'doParallel',
'doSNOW',
'dplR',
'dplyr',
'ellipse',
'emdbook',
'foreach',
'fs',
'furrr',
'future',
'getPass',
'ggmap',
'ggmcmc',
'ggplot2',
'ggpubr',
'ggrepel',
'glue',
'graphics',
'grDevices',
'grid',
'gridExtra',
'hdf5r',
'here',
'httr',
'IDPmisc',
'jsonlite',
'knitr',
'lattice',
'linkages',
'lqmm',
'Maeswrap',
'magrittr',
'markdown',
'MASS',
'Matrix',
'mclust',
'MCMCpack',
'methods',
'mgcv',
'minpack.lm',
'mlegp',
'mvbutils',
'mvtnorm',
'neonstore',
'neonUtilities',
'nimble',
'nneo',
'optparse',
'parallel',
'plotrix',
'png',
'prodlim',
'progress',
'pwr',
'R.utils',
'randtoolbox',
'raster',
'rcrossref',
'REddyProc',
'redland',
'reshape',
'reticulate',
'rjags',
'rjson',
'rlist',
'RPostgres',
'RPostgreSQL',
'Rpreles',
'RSQLite',
'sf',
'SimilarityMeasures',
'sirt',
'sp',
'stats',
'stringi',
'suntools',
'swfscMisc',
'terra',
'tibble',
'tictoc',
'tidyr',
'tidyselect',
'tidyverse',
'tools',
'traits',
'truncnorm',
'units',
'urltools',
'utils',
'withr',
'xtable',
'xts',
'zoo'
)
missing <- wanted[!(wanted %in% installed.packages()[,'Package'])]
install.packages(missing, lib = rlib)

# Install packages listed as Depends, Imports, Suggests
#    that list a minimum version.
# When the minimum is not satisfied in the fixed-date CRAN snapshot
#    used by our Docker images, we pull it in from an up-to-date mirror.
# (Assumes our CRAN uses the same URL scheme as Posit package manager)
options(repos = c(
    getOption('repos'),
    sub(r'(\d{4}-\d{2}-\d{2})', 'latest', getOption('repos'))
))
ensure_version <- function(pkg, version) {
    vers <- gsub('[^[:digit:].-]+', '', version)
    cmp <- get(gsub('[^<>=]+', '', version))
    ok <- requireNamespace(pkg, quietly = TRUE) &&
        cmp(packageVersion(pkg), vers)
    if (!ok) {
        remotes::install_version(pkg, version, dependencies = TRUE, upgrade = FALSE)
    }
}
ensure_version('abind', '>= 1.4.5')
ensure_version('coda', '>= 0.18')
ensure_version('geonames', '> 0.998')
ensure_version('lubridate', '>= 1.7.0')
ensure_version('magic', '>= 1.5.0')
ensure_version('mockery', '>= 0.4.3')
ensure_version('MODISTools', '>= 1.1.0')
ensure_version('ncdf4', '>= 1.15')
ensure_version('plyr', '>= 1.8.4')
ensure_version('purrr', '>= 0.2.3')
ensure_version('reshape2', '>= 1.4.2')
ensure_version('rlang', '>= 0.2.0')
ensure_version('rmarkdown', '>= 2.19')
ensure_version('stringr', '>= 1.1.0')
ensure_version('testthat', '>= 3.0.4')
ensure_version('TruncatedNormal', '>= 2.2')
ensure_version('vdiffr', '>= 1.0.2')
ensure_version('XML', '>= 3.98-1.4')
