# About the PEcAn Book

This book serves as documentation for the PEcAn Project. It contains descriptions of topics necessary to inform a beginner and advanced user as well as requisite materials for developers. It does not contain low-level descriptions of functions within PEcAn. Our aim for this documentation is to educate you about the PEcAn software, the possibilities of its usage, and the standards,expectations, and core workflows for developers.


## How to Contribute
If you wish to contribute to this book, we greatly welcome it! The same general steps to contributing PEcAn code to the main line can be used to contribute to this book.

### Editing the book yourself

1. Navigate to the main [ PEcAn github repository: https://github.com/PecanProject/pecan](https://github.com/PecanProject/pecan) and fork the repository to your github account.

2. Use `git clone` on the machine your are using to create a local copy of the repository. General instructions can be found [here](https://help.github.com/articles/cloning-a-repository/)

3. Navigate to the `book_source` directory and edit the page you would like to change using any text editor. Save your files in the  R markdown format (.Rmd).
    * If you are adding a new page, you must edit the `_bookdown.yml` file also and list your page in order for it to be properly indexed by gitbook.

4. Within the directory `book_source` diectory, execute `make`

5. Use `git add changedfile.Rmd` to stage your changes and then commit ` git commit -m "your message"` your changes and push (`git push`) them to your fork.

6. [Create a pull request](https://help.github.com/articles/creating-a-pull-request/), using github,  with a description of the changes you have made.



### Feedback/Comments/Suggestions
We want your ideas, thoughts, comments, and suggestions! This is an open-sourced project so please feel free to reach out
to us in the following ways:

**Github:** [https://github.com/PecanProject/pecan](https://github.com/PecanProject/pecan)
Serving as the main hub of communication surrounding PEcAn development, check out the issues section to see what is coming down the pipeline. If there is anything you feel you can contribute to, leave a comment.
​	
**Slack:** [https://pecanproject.slack.com/](https://pecanproject.slack.com/)
Slack serves as our day to day mode of communication. To join us in slack you will need to create an account first. This is done in 3 steps:

1. Request an [inivitation](https://publicslack.com/slacks/pecanproject/invites/new) to join slack, this will be send by email to address you provided.
2. <a id="slackreturn"></a>Check your inbox for an email from Slack with subject "Rob Kooper has invited you to join a Slack workspace". This email should have a link that you can click to join slack.
3. When you click a webpage will open up that asks you to create an account, once that is done you can login into the slack chatrooms.


**Email:** pecanproj[at]gmail.com
If you do not wish your communication with the team to be public, send us an email at the  address above and we will get back to you as soon as possible.

### Main Topics

This book is organized around these main topics:

**Basic User Guide** - Explains a simple setup of PEcAn and how to execute a basic run 

**Advanced User Guide- Web** - Explains the advanced features offered on our web interface
​	
**Advanced User Guide - Cmd Line** - Explains more advanced customization of PEcAn that can be run from the command line.
​	
**User Appendix** - Supplementary materials for the user section.

**PEcAn Workflow** - High Level explanation of the PEcAn workflow. 

**Development Guide** - Explains what you need to know in order to contibute code to PEcAn.
​	
**Appendix** - Supplementary materials for the developer section.
​	

## Using PEcAn

We have developed a number of demos and vignettes to guide your use of PEcAn's many capabilities:

|Type|Title|Web Link| Source Rmd|
|:--:|:---:|:------:|:---------:|
|Demo| Basic Run| [html](https://pecanproject.github.io/pecan-documentation/tutorials/Demo01.html) | [Rmd](https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/01_Demo_Basic_Run/Demo01.Rmd)|
|Demo| Uncertainty Analysis| [html](https://pecanproject.github.io/pecan-documentation/tutorials/Demo02.html)| [Rmd](https://github.com/PecanProject/pecan/tree/master/documentation/tutorials/02_Demo_Uncertainty_Analysis)|
|Demo| Output Analysis|html |[Rmd](https://github.com/PecanProject/pecan/tree/develop/documentation/tutorials/AnalyzeOutput)|
|Demo| MCMC |html|[Rmd](https://github.com/PecanProject/pecan/tree/develop/documentation/tutorials/MCMC)|
|Demo|Parameter Assimilation |html |[Rmd](https://github.com/PecanProject/pecan/tree/develop/documentation/tutorials/ParameterAssimilation)|
|Demo|State Assimilation|html|[Rmd](https://github.com/PecanProject/pecan/tree/develop/documentation/tutorials/StateAssimilation)|
|Demo| Sensitivity|html|[Rmd](https://github.com/PecanProject/pecan/tree/develop/documentation/tutorials/sensitivity)|
|Vignette|Allometries|html|[Rmd](https://github.com/PecanProject/pecan/blob/master/modules/allometry/vignettes/AllomVignette.Rmd)|
|Vignette|MCMC|html|[Rmd](https://github.com/PecanProject/pecan/blob/master/modules/assim.batch/vignettes/AssimBatchVignette.Rmd)|
|Vignette|Meteorological Data|html|[Rmd](https://github.com/PecanProject/pecan/tree/master/modules/data.atmosphere/vignettes)|
|Vignette|Meta-Analysis|html|[Rmd](https://github.com/PecanProject/pecan/blob/master/modules/meta.analysis/vignettes/single.MA_demo.Rmd)|
|Vignette|Photosynthetic Response Curves|html|[Rmd](https://github.com/PecanProject/pecan/blob/master/modules/photosynthesis/vignettes/ResponseCurves.Rmd)|
|Vignette|Priors|html|[Rmd](https://github.com/PecanProject/pecan/blob/master/modules/priors/vignettes/priors_demo.Rmd)|
|Vignette|Leaf Spectra:PROSPECT inversion|html|[Rmd](https://github.com/PecanProject/pecan/blob/master/modules/rtm/vignettes/pecanrtm.vignette.Rmd)|
