#-------------------------------------------------------------------------------
# Copyright (c) 2012 University of Illinois, NCSA.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the 
# University of Illinois/NCSA Open Source License
# which accompanies this distribution, and is available at
# http://opensource.ncsa.illinois.edu/license.html
#-------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------#
##' Convert BioCro output to netCDF
##'
##' Converts all output contained in a folder to netCDF.
##' Modified from on model2netcdf.sipnet and model2netcdf.ED2 by
##' Shawn Serbin and Mike Dietze
##' @name model2netcdf.BIOCRO
##' @title Function to convert biocro model output to standard netCDF format
##' @param outdir Location of biocro model output
##' @param run.id Name of biocro model output file.
##' @export
##' @author David LeBauer, Deepak Jaiswal
model2netcdf.BIOCRO <- function(outdir) {
  
  ### Read in model output in biocro format
  outfile <- file.path(outdir, "result.csv")
  result <- read.csv(outfile)
  result$s <- with(result, ((DayofYear -1) * 24 + Hour) * 3600)

  ## longname prefix station_* used for a point http://cf-pcmdi.llnl.gov/documents/cf-conventions/1.4/cf-conventions.html#scalar-coordinate-variables
  lat <- ncdim_def("lat", "degrees_east",
                   vals =  as.numeric(settings$run$site$lat),
                   longname = "station_latitude") 
  lon <- ncdim_def("lon", "degrees_north",
                   vals = as.numeric(settings$run$site$lon),
                   longname = "station_longitude")
  t <- ncdim_def(name = "time",
                 units = paste0("days since ",
                   year(settings$run$start.date),
                   "-01-01 00:00:00"),
                 vals = with(result, DayofYear + Hour/24),
                 calendar = "standard", unlim = TRUE)
  ## seconds per day
  vars <- list()
  ncvar_def.pecan <- function(name, units, longname,
                              dim = list(lon, lat, t),
                              missval = -999, prec = "float"){
    ans <- ncvar_def(name = name, units = units, dim = dim,
                     missval = missval, prec = "float")
    return(ans)
  }
  c2biomass <- 0.4
  vars <- list(
    TotLivBiom  = ncvar_def.pecan(name = "TotLivBiom",
      units = "kg C m-2",
      longname = "Total living bioimass"),
    RootBiom    =  ncvar_def.pecan(name = "RootBiom",
      units    = "kg C m-2",
      longname = "Total root biomass"),
    StemBiom     = ncvar_def.pecan(name = "StemBiom",
      units = "kg C m-2",
      longname = "Total stem biomass"),
    Evap = ncvar_def.pecan(name = "Evap",
      units = "kg m-2 s-1",
      longname = "Total Evaporation"),
    TVeg = ncvar_def.pecan(name = "TVeg",
      units = "kg m-2 s-1",
      longname = "Transpiration"),
    LAI = ncvar_def.pecan(name = "LAI",
      units = "m2 m-2",
      longname = "Leaf Area Index"))
  k <- ud.convert(1, "Mg/ha", "kg/m2") / c2biomass

  results <- with(result, list(
    TotLivBiom = ud.convert(Leaf + Root + Stem + Rhizome + Grain, "Mg/ha", "kg/m2") * 0.4, 
    RootBiom = ud.convert(Root,  "Mg/ha", "kg/m2") * 0.4,
    StemBiom = ud.convert(Stem, "Mg/ha", "kg/m2") * 0.4,
    Evap = ud.convert(SoilEvaporation + CanopyTrans, "Mg/ha/h", "kg/m2/s"),
    TVeg = ud.convert(CanopyTrans, "Mg/ha/h", "kg/m2/s"),
    LAI =  LAI))
  
  nc <- nc_create(filename = file.path(outdir, "result2.nc"),
                  vars = vars)
   
  ## Output netCDF data
  for(name in names(vars)) {
    ncatt_put(nc, varid = vars[[name]],
              attname = name,
              attval = results[[name]])
  }
  ncatt_put(nc, 0, "description",
            "This is an output from the BioCro Crop model generated by the model2netcdf.BIOCRO.R function in the PEcAn.BIOCRO package; see github.com:PecanProject/pecan/wiki for more information")
  nc_close(nc) 
}

####################################################################################################
### EOF.  End of R script file.              
####################################################################################################
