#' @name EDR
#' @title ED radiative transfer module (EDR) wrapper function
#' @description This function provides a convenient way to call the ED 
#' radiative transfer module (EDR, which simulates full spectral return of an 
#' ED patch for a given point in time) directly from R.
#' @param paths List of relevant paths. Must contain the following:
#' `ed2in` -- Path to ED2IN file for the original ED run. If this is `NA`, the 
#' function assumes that the ED2IN file in `output.path` is already up-to-date 
#' and skips the analysis step.
#' `history` -- Path and prefix for history file for the run of interest;
#' `edr.exe` -- Path to EDR executable
#' @param RT.matrix Matrix of wavelengths, reflectance, and transmittance 
#' values. Matrix must have column names "wl" (wavelength), "R" (reflectance), 
#' and "T" (transmittance). Such a matrix is returned by default by all 
#' versions of PROSPECT in this package.
#' @param par.wl Vector of wavelengths defining PAR region
#' @param nir.wl Vector of wavelengths defining NIR region
#' @param datetime POSIXlt object defining the date and at which the run will 
#' take place. N datetime POSIXlt object defining the date and at which the run 
#' will take place. Note that runs at night and during the winter can give poor 
#' results.
#' @param history.prefix Prefix in histroy file name. Will be appended to 
#' history path.
#' @param change.history.time Logical. If `TRUE`, rename the history file to 
#' the time specified in `datetime`. Default = TRUE.
#' @param output.path Path to store all output files. Default is current 
#' working directory.
#' @param clean Logical. If `TRUE`, remove all files generated by this function 
#' (e.g. cloned history file, ED2IN, output HDF files).

EDR <- function(paths,
                RT.matrix,
                par.wl,
                nir.wl,
                datetime,
                history.prefix = "history",
                change.history.time = TRUE,
                output.path = getwd(),
                clean = FALSE){

# Extract paths
    ed2in.path <- paths$ed2in
    history.path <- paths$history
    edr.exe.path <- paths$edr.exe

# Process datetime
    if(!any(grepl("POSIX", class(datetime)))) stop("datetime is not POSIX")
    nextdate <- as.Date(datetime) + 1   # For 'terminating' the run
    day <- strftime(datetime, "%d")
    month <- strftime(datetime, "%m")
    year <- strftime(datetime, "%Y")
    starttime <- '0000'     # Not the RTM time, but the "model" time -- shouldn't matter
    nextday <- strftime(nextdate, "%d")
    nextmonth <- strftime(nextdate, "%m")
    nextyear <- strftime(nextdate, "%Y")
    nexttime <- '0000'      # Not the RTM time, but the "model" time -- shouldn't matter
    time.ed2in <- strftime(datetime, "%H%M")
    time.history <- strftime(datetime, "%H%M%S")

# Preprocess history file
    if(change.history.time){ # Otherwise, skip this step
        history.search <- sprintf("%$1s-S-%$2s-%$3s-%$4s",
                                history.prefix,
                                year, month, day)
        history.name <- list.files(history.path, history.search)
        history.full.path <- file.path(history.path, history.name)
        if(length(history.name) > 1) stop("Multiple history files matched")
        if(length(history.name) == 0) stop("No history files found")
        history.new.name <- gsub('([[:digit:]]{6})', time.history, history.name)
        history.new.path <- file.path(output.path, history.new.name)
        file.copy(history.full.path, history.new.path)
        history.full.prefix <- file.path(output.path, history.prefix)
    } else { 
# Use the unaltered history file given in by history.path and history.prefix
        history.full.prefix <- file.path(history.path, history.prefix)
    }

# Preprocess ED2IN
    if(!is.na(ed2in.path)){     # Otherwise, skip this step
        file.copy(ed2in.path, output.path) # Copy ED2IN to local directory
# Modify ED2IN
        ed2in.local.path <- file.path(output.path, "ED2IN")
        ed2in <- readLines(ed2in.local.path)
        ed2in <- gsub('(NL%RUNTYPE).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', 'HISTORY'))
# Start day and time
        ed2in <- gsub('(NL%IMONTHA).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', month), ed2in)
        ed2in <- gsub('(NL%IDATEA).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', day), ed2in)
        ed2in <- gsub('(NL%IYEARA).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', year), ed2in)
        ed2in <- gsub('(NL%ITIMEA).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', starttime), ed2in)
# End date and time
        ed2in <- gsub('(NL%IMONTHZ).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', nextmonth), ed2in)
        ed2in <- gsub('(NL%IDATEZ).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', nextday), ed2in)
        ed2in <- gsub('(NL%IYEARZ).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', nextyear), ed2in)
        ed2in <- gsub('(NL%ITIMEZ).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', nexttime), ed2in)
# Output file location
        ed2in <- gsub('(NL%FFILOUT).*', 
                      sprintf('\\1 = %s/analysis  !! MODIFIED BY R WRAPPER', output.path), ed2in)
        ed2in <- gsub('(NL%SFILOUT).*', 
                      sprintf('\\1 = %s/history  !! MODIFIED BY R WRAPPER', output.path), ed2in)
# Input (history) file location
        ed2in <- gsub('(NL%SFILIN).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', history.full.prefix), ed2in)
# History file information
        ed2in <- gsub('(NL%ITIMEH).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', time.ed2in), ed2in)
        ed2in <- gsub('(NL%IDATEH).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', day), ed2in)
        ed2in <- gsub('(NL%IMONTHH).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', month), ed2in)
        ed2in <- gsub('(NL%IYEARH).*', 
                      sprintf('\\1 = %s  !! MODIFIED BY R WRAPPER', year), ed2in)
# Write resulting ED2IN to file
        write(ed2in, file = 'ED2IN')
    }

