# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pinvbayes <- function(ngibbs, Observed, adapt, adj_min, p4data) {
    .Call('PEcAnRTM_pinvbayes', PACKAGE = 'PEcAnRTM', ngibbs, Observed, adapt, adj_min, p4data)
}

prospect4 <- function(N, Cab, Cw, Cm, p4data) {
    .Call('PEcAnRTM_prospect4', PACKAGE = 'PEcAnRTM', N, Cab, Cw, Cm, p4data)
}

