## FBB_summary
sink(saveFileSum)
print(paste("LEAF",leaf))
print(paste("Iterations:",niter))
print(paste("Start:",start))  
print(paste("End:",end))  
print(paste("Thin:",thin))
print(paste("Used Iterations:",(end-start+1)*nchains/thin))  
print("---------------------------------------------")
print("MEAN, SD, q2.5, q97.5")
print(paste("Vcmax:",mean.Vcmax, sd.Vcmax, q25.Vcmax, q975.Vcmax, sep=",")) 
print(paste("Jmax:",mean.Jmax, sd.Jmax, q25.Jmax, q975.Jmax, sep=","))
print(paste("R:",mean.R, sd.R, q25.R, q975.R, sep=","))
print(paste("Gstar:",mean.Gstar, sd.Gstar, q25.Gstar, q975.Gstar, sep=","))
print(paste("alpha:",mean.alpha, sd.alpha, q25.alpha, q975.alpha, sep=","))
print(paste("m:",mean.m, sd.m, q25.m, q975.m, sep=","))
print(paste("g0:",mean.g0, sd.g0, q25.g0, q975.g0, sep=","))
print(paste("tauF:",mean.tauF, sd.tauF, q25.tauF, q975.tauF, sep=","))
print(paste("tauBB:",mean.tauBB, sd.tauBB, q25.tauBB, q975.tauBB, sep=","))
print("---------------------------------------------")
print("PREDICTED VALUES")
print(paste("An-mean:",mean.pred.An))
print(paste("gs-mean:",mean.pred.gs))
print(paste("An-sd:",sd.pred.An))
print(paste("gs-sd:",sd.pred.gs))
print(paste("An-q25:",q25.pred.An))
print(paste("gs-q25:",q25.pred.gs))
print(paste("An-q975:",q975.pred.An))
print(paste("gs-q975:",q975.pred.gs))
print("---------------------------------------------")
print(paste("Farquhar DIC:",DIC.An))
print(paste("Ball-Berry DIC:",DIC.gs))
print("---------------------------------------------")
print("Acceptrance Rates")
print(accept)
sink()
summary = data.frame(mean.Vcmax, sd.Vcmax, mean.Jmax, sd.Jmax, mean.R, sd.R, mean.Gstar, sd.Gstar, mean.alpha, sd.alpha, mean.m, sd.m, mean.g0, sd.g0, mean.tauF, sd.tauF, mean.tauBB, sd.tauBB, DIC.An, DIC.gs)
write.csv(summary,file=paste(SaveLeafDir, runName, "_summary.csv", sep=""))