# PEcAn Models {#pecan-models}

This section will contain information about all models and output variables that are supported by PEcAn.

| Model Name | Available in the VM | Prescribed Inputs | Input Functions/Values | Restart Function |
| -- | -- | -- | -- | -- |
| [BioCro](#models-biocro) | Yes | Yes | Yes| No |
| [CLM](#models-clm)| No | No | No| No |
| [DALEC](#models-dalec)| Yes | Yes | Yes| No |
| [ED2](#models-ed)| Yes | Yes | Yes| Yes |
| FATES | No | Yes | | No|
| [GDAY](#models-gday) | No | No | No| No |
| [LINKAGES](#models-linkages) | Yes | Yes | Yes| Yes |
| [LPJ-GUESS](#models-lpjguess)| No | Yes | No | No |
| [MAESPA](#models-maespa)| Yes | Yes | No | No |
| [PRELES](#models-preles) | Yes | Yes | Partially | No |
| [SiPNET](#models-sipnet)| Yes | Yes | Yes| Yes |
| [STICS](#models-stics)| Yes | Yes | No | No |

*Available in the VM* - Denotes if a model is publicly available with PEcAn.

*Prescribed Inputs* - Denotes whether or not PEcAn can prescribe inputs.

*Input Functions/Values* - Denotes whether or not PEcAn has functions to fully produce a model's Input values. 

*Restart Function* - Denotes status of model data assimilation capabilities.


**Output Variables**

PEcAn converts all model outputs to a single [Output Standards]. This standard evolved out of MsTMIP project, which is itself based on NACP, LBA, and other model-intercomparison projects. This standard was expanded for the PalEON MIP and the needs of the PEcAn modeling community to support variables not in these standards.

_Model developers_: do not add variables to your PEcAn output without first adding them to the PEcAn standard table! Also, do not create new variables equivalent to existing variables but just with different names or units. 
