#### CLM-FATES

Prerequisites
```
sudo apt-get upgrade libnetcdf-dev
sudo apt-get install subversion
sudo apt-get install csh
sudo apt-get install cmake
sudo ln -s /usr/bin/make /usr/bin/gmake
sudo rm /bin/sh
sudo ln -s /bin/bash /bin/sh

wget https://github.com/Unidata/netcdf-fortran/archive/v4.4.4.tar.gz
cd netcdf-4.4.4
./configure
make
sudo make install
```
you might need to mess around with installing netcdf and netcdf-fortran to get a version FATES likes...

Get code from Github (currently private) and go to cime/scripts directory
```
git clone git@github.com:NGEET/ed-clm.git
cd ed-clm/cime/scripts/
```
Within CLM-FATES, to be able to build an executable we need to create a reference run. We'll also use this reference run to grab defaults from, so we'll be registering the location of both the reference **case** (location of executable, scripts, etc) and the reference **inputs** with the PEcAn database. To begin, copy reference run script from pecan
```
cp ~/pecan/models/fates/inst/create_1x1_ref_case.sh .
```
Edit reference case script to set NETCDF_HOME, CROOT (reference run case), DIN_LOC_ROOT (reference run inputs). Also, make sure DIN_LOC_ROOT exists as FATES will not create it itself. Then run the script
```
./create_1x1_ref_case.sh
```
Be aware that this script WILL ask you for your password on the NCAR server to download the reference case input data (the guest password may work, haven't tried this). If it gives an error at the pio stage check the log, but the most likely error is it being unable to find a version of netcdf it likes.

Once FATES is installed, set the whole reference case directory as the Model path (leave filename blank) and set the whole inputs directory as an Input with format clm_defaults.