---
title: "Initial Ensemble Forecast, no SDA"
author: "MCD"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(terra)
```

## Simple ensemble run, based on workflow.R
```{r}
library("PEcAn.all")
settings = readRDS("/projectnb/dietzelab/dietze/hf_landscape_SDA/test01/pecan.RDS")
settings <- PEcAn.settings::prepare.settings(settings, force = FALSE)

settings <- PEcAn.workflow::runModule.run.write.configs(settings)
PEcAn.workflow::runModule_start_model_runs(settings, stop.on.error = FALSE)
#runModule.get.results(settings)
#runModule.run.ensemble.analysis(settings, TRUE)
```

## process forecast output into EFI long csv format
```{r}
runModule.PEcAn2EFI <- function(settings) {
  if (PEcAn.settings::is.MultiSettings(settings)) {
    return(PEcAn.settings::papply(settings, runModule.PEcAn2EFI))
  } else if (PEcAn.settings::is.Settings(settings)) {
    return(PEcAn2EFI(settings))
  } else {
    stop("runModule.get.results only works with Settings or MultiSettings")
  }
}

PEcAn2EFI <- function(s=settings){
  #s = settings[[1]] ## testing
  outdir <- s$modeloutdir

  # ## load ensemble objects, used code from get.results
  # if (!is.null(ens.ensemble.id)) {
  #   fname <- ensemble.filename(s, "ensemble.samples", "Rdata", 
  #                              ensemble.id = ens.ensemble.id, 
  #                              all.var.yr = TRUE)
  # } else if (!is.null(s$ensemble$ensemble.id)) {
  #   ens.ensemble.id <- s$ensemble$ensemble.id
  #   fname <- ensemble.filename(s, "ensemble.samples", "Rdata",
  #                              ensemble.id = ens.ensemble.id, 
  #                              all.var.yr = TRUE)
  # } else {
  #   fname <- file.path(outdir, "samples.Rdata")
  # }     
  # if (!file.exists(fname)) {
  #   PEcAn.logger::logger.severe("No ensemble samples file found!")
  # }
  # load(fname)
  # if (!exists("ens.run.ids")) {
  #   ens.run.ids <- runs.samples$ens
  # }
  ens.run.ids = paste("ENS",
                      formatC(1:s$ensemble$size, width = 5, format = "d", flag = "0"),
                      s$run$site$id,
                      sep="-"
                      )
  
  variable = s$ensemble$variable
  ensemble.output <- list()
  for (row in seq_along(ens.run.ids)) { #rownames(ens.run.ids)
    ## read output
    #run.id <- ens.run.ids[row, "id"]
    run.id <- ens.run.ids[row]
    PEcAn.logger::logger.info("reading ensemble output from run id: ", format(run.id, scientific = FALSE))
    ensemble.output[[row]] <- PEcAn.utils::read.output(run.id, file.path(outdir, run.id), start.year, end.year, variables=NULL)
    
    ## reprocess time_bounds
    doy = as.vector(ensemble.output[[row]]$time_bounds[1,])  ## day of year
    years = c(which(doy < 0.00001),length(doy)+1) ## get breaks between years
    if(years[1] != 1) years = c(1,years) ## add current year if not start of year
    years = rep(lubridate::year(start_date):lubridate::year(end_date),times=diff(years)) ## convert to years
    tod = lubridate::as_datetime(lubridate::seconds_to_period(floor((doy - floor(doy)) * 60 *60))) ## time of day
    lubridate::year(tod) <- years   
    lubridate::yday(tod) <- floor(doy)    
    ensemble.output[[row]]$time_bounds = tod
    
    ## convert to data frame
    ensemble.output[[row]]  = as.data.frame(ensemble.output[[row]]) %>% 
      dplyr::mutate(
        parameter = row,
        reference_datetime = lubridate::as_datetime(s$run$start.date),
        site_id = s$run$site$id
      )
  }
  names(ensemble.output) = ens.run.ids
  
  return(dplyr::bind_rows(ensemble.output))
}

out = data.table::rbindlist(runModule.PEcAn2EFI(settings))
saveRDS(out,"out.RDS")

```


## pull together, weight, and visualize outputs
```{r}
if(!exists("out")){
  out = readRDS("out.RDS")
}

## plot example time-series
sitets <- out[[1]] %>% 
  dplyr::select(NPP,time_bounds) %>%
  dplyr::mutate(day = lubridate::round_date(time_bounds,"day")) %>% 
  dplyr::group_by(day) %>% 
  dplyr::summarise(mu = mean(NPP),lci = quantile(NPP,0.025),uci=quantile(NPP,0.975))
  
ggplot2::ggplot(sitets, aes(x = day, y = mu)) + 
  geom_line(col='black') + 
  geom_ribbon(aes(ymin = lci, ymax = uci), alpha = 0.1) +
  labs(x="time",y="NPP")

cumNPP <- out[[1]] %>%
  dplyr::select(NPP,time_bounds,parameter) %>%  ## first, calculate cumulative sum for each ensemble member
  dplyr::group_by(parameter) %>%
  dplyr::mutate(cumNPP = cumsum(NPP)) %>%
  dplyr::ungroup() %>% dplyr::select(-parameter) %>% ## drop ensemble dimension, then calculate daily mean & CI
  dplyr::mutate(day = lubridate::round_date(time_bounds,"day")) %>% 
  dplyr::group_by(day) %>% 
  dplyr::summarise(mu = mean(cumNPP),lci = quantile(cumNPP,0.025),uci=quantile(cumNPP,0.975))

ggplot2::ggplot(cumNPP, aes(x = day, y = mu)) + 
  geom_line(col='black') + 
  geom_ribbon(aes(ymin = lci, ymax = uci), alpha = 0.1) +
  labs(x="time",y="NPP")
```

## spatial visualizations
```{r}
tower_lonlat = data.frame(lon=-72.17265,lat=42.53691)
tower_utm    = c(732183.98,4713266.18)
if(!exists("patches")){
  patches = read.csv("patches.csv")
}
if(!exists("patchMap")){
  patchMap <- terra::rast("patches.tif")
  pmap <- project(patchMap, "+proj=longlat",method="near")
  plot(pmap)
  points(tower_lonlat[1],tower_lonlat[2])
  tow = extract(pmap,tower_lonlat)
}
if(!exists("o2")){
  o2 <- data.table::rbindlist(out)
}

## calculate daily means
dm <- o2 %>% dplyr::select(NPP,time_bounds,site_id) %>%
  dplyr::mutate(day = lubridate::round_date(time_bounds,"day")) %>% 
  dplyr::group_by(day,site_id) %>% 
  dplyr::summarise(mu = mean(NPP),lci = quantile(NPP,0.025),uci=quantile(NPP,0.975),.groups = "drop")

## plot example maps of mean and uncertainties
foo = dm[dm$day == as.Date("2016-07-04"),]
nmap = pmap
for(i in seq_len(nrow(patches))){
  nmap[pmap == i] = foo$mu[i]
}
plot(nmap)

## animated map
```



## landscape-scale weighted time-series
```{r}


```

