library(ncdf4)
library(ncdf4.helpers)
#Read in .nc files
HARV.nc <- list.files("/projectnb/dietzelab/ahelgeso/NOAA_met_data/noaa/half_hour/HARV/2021-06-01/", full.names = TRUE)

#Read in varibles  
assign(paste0("harv.nc", 1), ncdf4::nc_open(HARV.nc[1]))

var <- ncdf4.helpers::nc.get.variable.list(harv.nc1)

for (j in 1:length(HARV.nc)) {
  
  for (k in 1:length(var)) {
    assign(paste0("harv",j, "_", var[k]), mean(ncdf4::ncvar_get(ncdf4::nc_open(HARV.nc[j]), varid = var[k])))
    
  }
}
#Calculate means
air_temperature <- mean(harv1_air_temperature, 
                 harv2_air_temperature,
                 harv3_air_temperature,
                 harv4_air_temperature,
                 harv5_air_temperature,
                 harv6_air_temperature,
                 harv7_air_temperature,
                 harv8_air_temperature,
                 harv9_air_temperature,
                 harv10_air_temperature,
                 harv11_air_temperature,
                 harv12_air_temperature,
                 harv13_air_temperature,
                 harv14_air_temperature,
                 harv15_air_temperature,
                 harv16_air_temperature,
                 harv17_air_temperature,
                 harv18_air_temperature,
                 harv19_air_temperature,
                 harv20_air_temperature,
                 harv21_air_temperature,
                 harv22_air_temperature,
                 harv23_air_temperature,
                 harv24_air_temperature,
                 harv25_air_temperature,
                 harv26_air_temperature,
                 harv27_air_temperature,
                 harv28_air_temperature,
                 harv29_air_temperature,
                 harv30_air_temperature,
                 harv31_air_temperature)

air_pressure <- mean(harv1_air_pressure, 
                  harv2_air_pressure,
                  harv3_air_pressure,
                  harv4_air_pressure,
                  harv5_air_pressure,
                  harv6_air_pressure,
                  harv7_air_pressure,
                  harv8_air_pressure,
                  harv9_air_pressure,
                  harv10_air_pressure,
                  harv11_air_pressure,
                  harv12_air_pressure,
                  harv13_air_pressure,
                  harv14_air_pressure,
                  harv15_air_pressure,
                  harv16_air_pressure,
                  harv17_air_pressure,
                  harv18_air_pressure,
                  harv19_air_pressure,
                  harv20_air_pressure,
                  harv21_air_pressure,
                  harv22_air_pressure,
                  harv23_air_pressure,
                  harv24_air_pressure,
                  harv25_air_pressure,
                  harv26_air_pressure,
                  harv27_air_pressure,
                  harv28_air_pressure,
                  harv29_air_pressure,
                  harv30_air_pressure,
                  harv31_air_pressure)

relative_humidity <- mean(harv1_relative_humidity, 
                harv2_relative_humidity,
                harv3_relative_humidity,
                harv4_relative_humidity,
                harv5_relative_humidity,
                harv6_relative_humidity,
                harv7_relative_humidity,
                harv8_relative_humidity,
                harv9_relative_humidity,
                harv10_relative_humidity,
                harv11_relative_humidity,
                harv12_relative_humidity,
                harv13_relative_humidity,
                harv14_relative_humidity,
                harv15_relative_humidity,
                harv16_relative_humidity,
                harv17_relative_humidity,
                harv18_relative_humidity,
                harv19_relative_humidity,
                harv20_relative_humidity,
                harv21_relative_humidity,
                harv22_relative_humidity,
                harv23_relative_humidity,
                harv24_relative_humidity,
                harv25_relative_humidity,
                harv26_relative_humidity,
                harv27_relative_humidity,
                harv28_relative_humidity,
                harv29_relative_humidity,
                harv30_relative_humidity,
                harv31_relative_humidity)

surface_downwelling_longwave_flux_in_air <- mean(harv1_surface_downwelling_longwave_flux_in_air, 
                      harv2_surface_downwelling_longwave_flux_in_air,
                      harv3_surface_downwelling_longwave_flux_in_air,
                      harv4_surface_downwelling_longwave_flux_in_air,
                      harv5_surface_downwelling_longwave_flux_in_air,
                      harv6_surface_downwelling_longwave_flux_in_air,
                      harv7_surface_downwelling_longwave_flux_in_air,
                      harv8_surface_downwelling_longwave_flux_in_air,
                      harv9_surface_downwelling_longwave_flux_in_air,
                      harv10_surface_downwelling_longwave_flux_in_air,
                      harv11_surface_downwelling_longwave_flux_in_air,
                      harv12_surface_downwelling_longwave_flux_in_air,
                      harv13_surface_downwelling_longwave_flux_in_air,
                      harv14_surface_downwelling_longwave_flux_in_air,
                      harv15_surface_downwelling_longwave_flux_in_air,
                      harv16_surface_downwelling_longwave_flux_in_air,
                      harv17_surface_downwelling_longwave_flux_in_air,
                      harv18_surface_downwelling_longwave_flux_in_air,
                      harv19_surface_downwelling_longwave_flux_in_air,
                      harv20_surface_downwelling_longwave_flux_in_air,
                      harv21_surface_downwelling_longwave_flux_in_air,
                      harv22_surface_downwelling_longwave_flux_in_air,
                      harv23_surface_downwelling_longwave_flux_in_air,
                      harv24_surface_downwelling_longwave_flux_in_air,
                      harv25_surface_downwelling_longwave_flux_in_air,
                      harv26_surface_downwelling_longwave_flux_in_air,
                      harv27_surface_downwelling_longwave_flux_in_air,
                      harv28_surface_downwelling_longwave_flux_in_air,
                      harv29_surface_downwelling_longwave_flux_in_air,
                      harv30_surface_downwelling_longwave_flux_in_air,
                      harv31_surface_downwelling_longwave_flux_in_air)

surface_downwelling_shortwave_flux_in_air <- mean(harv1_surface_downwelling_shortwave_flux_in_air, 
                       harv2_surface_downwelling_shortwave_flux_in_air,
                       harv3_surface_downwelling_shortwave_flux_in_air,
                       harv4_surface_downwelling_shortwave_flux_in_air,
                       harv5_surface_downwelling_shortwave_flux_in_air,
                       harv6_surface_downwelling_shortwave_flux_in_air,
                       harv7_surface_downwelling_shortwave_flux_in_air,
                       harv8_surface_downwelling_shortwave_flux_in_air,
                       harv9_surface_downwelling_shortwave_flux_in_air,
                       harv10_surface_downwelling_shortwave_flux_in_air,
                       harv11_surface_downwelling_shortwave_flux_in_air,
                       harv12_surface_downwelling_shortwave_flux_in_air,
                       harv13_surface_downwelling_shortwave_flux_in_air,
                       harv14_surface_downwelling_shortwave_flux_in_air,
                       harv15_surface_downwelling_shortwave_flux_in_air,
                       harv16_surface_downwelling_shortwave_flux_in_air,
                       harv17_surface_downwelling_shortwave_flux_in_air,
                       harv18_surface_downwelling_shortwave_flux_in_air,
                       harv19_surface_downwelling_shortwave_flux_in_air,
                       harv20_surface_downwelling_shortwave_flux_in_air,
                       harv21_surface_downwelling_shortwave_flux_in_air,
                       harv22_surface_downwelling_shortwave_flux_in_air,
                       harv23_surface_downwelling_shortwave_flux_in_air,
                       harv24_surface_downwelling_shortwave_flux_in_air,
                       harv25_surface_downwelling_shortwave_flux_in_air,
                       harv26_surface_downwelling_shortwave_flux_in_air,
                       harv27_surface_downwelling_shortwave_flux_in_air,
                       harv28_surface_downwelling_shortwave_flux_in_air,
                       harv29_surface_downwelling_shortwave_flux_in_air,
                       harv30_surface_downwelling_shortwave_flux_in_air,
                       harv31_surface_downwelling_shortwave_flux_in_air)

precipitation_flux <- mean(harv1_precipitation_flux, 
                     harv2_precipitation_flux,
                     harv3_precipitation_flux,
                     harv4_precipitation_flux,
                     harv5_precipitation_flux,
                     harv6_precipitation_flux,
                     harv7_precipitation_flux,
                     harv8_precipitation_flux,
                     harv9_precipitation_flux,
                     harv10_precipitation_flux,
                     harv11_precipitation_flux,
                     harv12_precipitation_flux,
                     harv13_precipitation_flux,
                     harv14_precipitation_flux,
                     harv15_precipitation_flux,
                     harv16_precipitation_flux,
                     harv17_precipitation_flux,
                     harv18_precipitation_flux,
                     harv19_precipitation_flux,
                     harv20_precipitation_flux,
                     harv21_precipitation_flux,
                     harv22_precipitation_flux,
                     harv23_precipitation_flux,
                     harv24_precipitation_flux,
                     harv25_precipitation_flux,
                     harv26_precipitation_flux,
                     harv27_precipitation_flux,
                     harv28_precipitation_flux,
                     harv29_precipitation_flux,
                     harv30_precipitation_flux,
                     harv31_precipitation_flux)

specific_humidity <- mean(harv1_specific_humidity, 
                 harv2_specific_humidity,
                 harv3_specific_humidity,
                 harv4_specific_humidity,
                 harv5_specific_humidity,
                 harv6_specific_humidity,
                 harv7_specific_humidity,
                 harv8_specific_humidity,
                 harv9_specific_humidity,
                 harv10_specific_humidity,
                 harv11_specific_humidity,
                 harv12_specific_humidity,
                 harv13_specific_humidity,
                 harv14_specific_humidity,
                 harv15_specific_humidity,
                 harv16_specific_humidity,
                 harv17_specific_humidity,
                 harv18_specific_humidity,
                 harv19_specific_humidity,
                 harv20_specific_humidity,
                 harv21_specific_humidity,
                 harv22_specific_humidity,
                 harv23_specific_humidity,
                 harv24_specific_humidity,
                 harv25_specific_humidity,
                 harv26_specific_humidity,
                 harv27_specific_humidity,
                 harv28_specific_humidity,
                 harv29_specific_humidity,
                 harv30_specific_humidity,
                 harv31_specific_humidity)

cloud_area_fraction <- mean(harv1_cloud_area_fraction, 
                 harv2_cloud_area_fraction,
                 harv3_cloud_area_fraction,
                 harv4_cloud_area_fraction,
                 harv5_cloud_area_fraction,
                 harv6_cloud_area_fraction,
                 harv7_cloud_area_fraction,
                 harv8_cloud_area_fraction,
                 harv9_cloud_area_fraction,
                 harv10_cloud_area_fraction,
                 harv11_cloud_area_fraction,
                 harv12_cloud_area_fraction,
                 harv13_cloud_area_fraction,
                 harv14_cloud_area_fraction,
                 harv15_cloud_area_fraction,
                 harv16_cloud_area_fraction,
                 harv17_cloud_area_fraction,
                 harv18_cloud_area_fraction,
                 harv19_cloud_area_fraction,
                 harv20_cloud_area_fraction,
                 harv21_cloud_area_fraction,
                 harv22_cloud_area_fraction,
                 harv23_cloud_area_fraction,
                 harv24_cloud_area_fraction,
                 harv25_cloud_area_fraction,
                 harv26_cloud_area_fraction,
                 harv27_cloud_area_fraction,
                 harv28_cloud_area_fraction,
                 harv29_cloud_area_fraction,
                 harv30_cloud_area_fraction,
                 harv31_cloud_area_fraction)

wind_speed <- mean(harv1_wind_speed, 
             harv2_wind_speed,
             harv3_wind_speed,
             harv4_wind_speed,
             harv5_wind_speed,
             harv6_wind_speed,
             harv7_wind_speed,
             harv8_wind_speed,
             harv9_wind_speed,
             harv10_wind_speed,
             harv11_wind_speed,
             harv12_wind_speed,
             harv13_wind_speed,
             harv14_wind_speed,
             harv15_wind_speed,
             harv16_wind_speed,
             harv17_wind_speed,
             harv18_wind_speed,
             harv19_wind_speed,
             harv20_wind_speed,
             harv21_wind_speed,
             harv22_wind_speed,
             harv23_wind_speed,
             harv24_wind_speed,
             harv25_wind_speed,
             harv26_wind_speed,
             harv27_wind_speed,
             harv28_wind_speed,
             harv29_wind_speed,
             harv30_wind_speed,
             harv31_wind_speed)
#Add var means to new .nc file


