## Download GFDL
The Downlad.GFDL function assimilates 3 hour frequency CMIP5 outputs generated by multiple GFDL models. GFDL developed several distinct modeling streams on the timescale of CMIP5 and AR5. These models include CM3, ESM2M and ESM2G with a spatial resolution of 2 degrees latitude by 2.5 degrees longitude. Each model has future outputs for the AR5 Representative Concentration Pathways ranging from 2006-2100.  

## CM3
GFDL’s CMIP5 experiments with CM3 included many of the integrations found in the long-term CMIP5 experimental design. The focus of this physical climate model is on the role of aerosols, aerosol-cloud interactions, and atmospheric chemistry in climate variability and climate change.

## ESM2M & ESM2G

Two new models representing ocean physics with alternative numerical frameworks to explore the implications of some of the fundamental assumptions embedded in these models. Both ESM2M and ESM2G utilize a more advanced land model, LM3, than was available in ESM2.1 including a variety of enhancements (Milly et al., in prep). GFDL’s CMIP5 experiments with Earth System Models included many of the integrations found in the long-term CMIP5 experimental design. The ESMs, by design, close the carbon cycle and are used to study the impact of climate change on ecosystems, ecosystem changes on climate and human activities on ecosystems.

For more information please navigate [here](https://gfdl.noaa.gov/cmip)

<table width=100%>
    <th></th>
    <th>CM#</th>
    <th>ESM2M</th>
    <th>ESM2G</th>
    
    <tr>
      <td>rcp26</td>
      <td></td>      
      <td>r1i1p1</td>
      <td>r1i1p1</td>      
    </tr>
    <tr>
      <td>rcp45</td>
      <td>r1i1p1, r3i1p1,r5i1p1</td>      
      <td>r1i1p1</td>
      <td>r1i1p1</td>      
    </tr>
    <tr>
      <td>rcp60</td>
      <td></td>      
      <td>r1i1p1</td>
      <td>r1i1p1</td>      
    </tr>
    <tr>
      <td>rcp85</td>
      <td>r1i1p1</td>      
      <td>r1i1p1</td>
      <td>r1i1p1</td>      
    </tr>
    
    