# ----------------------------------------------------------------------
# PECAN FOR MODEL BASE IMAGE
# ----------------------------------------------------------------------
FROM pecan/depends
MAINTAINER Rob Kooper <kooper@illinois.edu>

# What version of PEcAn
ARG PECAN_VERSION="develop"
ARG PECAN_GIT_BRANCH="unknown"
ARG PECAN_GIT_CHECKSUM="unknown"
ARG PECAN_GIT_DATE="unknown"

# variables to store in docker image
ENV PECAN_VERSION=${PECAN_VERSION} \
    PECAN_GIT_BRANCH=${PECAN_GIT_BRANCH} \
    PECAN_GIT_CHECKSUM=${PECAN_GIT_CHECKSUM} \
    PECAN_GIT_DATE=${PECAN_GIT_DATE}

# ----------------------------------------------------------------------
# SETUP 
# ----------------------------------------------------------------------
WORKDIR /work

# ----------------------------------------------------------------------
# INSTALL PECAN
# ----------------------------------------------------------------------

# copy folders
COPY Makefile /pecan/
COPY base     /pecan/base/
COPY modules  /pecan/modules/
COPY models   /pecan/models/

RUN cd /pecan && make

# COPY WORKFLOW
COPY web/workflow.R /work/

# COMMAND TO RUN
CMD Rscript --vanilla workflow.R | tee workflow.Rout
