FROM php:apache
MAINTAINER Rob Kooper <kooper@illinois.edu>

# install rabbitmq and postgresql extentions
RUN apt-get update \
    && apt-get install -y \
        libpq-dev \
        librabbitmq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install -j$(nproc) pdo pdo_pgsql \
    && pecl install amqp \
    && docker-php-ext-enable amqp

# copy webpages
COPY documentation/index_vm.html /var/www/html/index.html
COPY web /var/www/html/pecan/
COPY docker/config.docker.php /var/www/html/pecan/config.php
