! BEGIN DART PREPROCESS KIND LIST
! LAI, KIND_LEAF_AREA_INDEX, COMMON_CODE
! GLF, KIND_GREEN_LEAF_FACTOR, COMMON_CODE
! PB, KIND_PRESCRIBED_EXPONENT, COMMON_CODE
! FLR, KIND_FILLER, COMMON_CODE
! END DART PREPROCESS KIND LIST
