# Available Meteorological Drivers

## Ameriflux

Scale: site

Resolution: 30 or 60 min

Availability: varies by site http:\/\/ameriflux.lbl.gov\/data\/data-availability\/

Notes: Old ORNL server, use is deprecated

## AmerifluxLBL

Scale: site

Resolution: 30 or 60 min

Availability: varies by site http:\/\/ameriflux.lbl.gov\/data\/data-availability\/

Notes: new Lawrence Berkeley Lab server

## Fluxnet2015

Scale: site

Resolution: 30 or 60 min

Availability: varies by site [http:\/\/fluxnet.fluxdata.org\/sites\/site-list-and-pages](http://fluxnet.fluxdata.org/sites/site-list-and-pages/)

Notes: Fluxnet 2015 synthesis product. Does not cover all FLUXNET sites

## NARR

Scale: North America

Resolution: 3 hr, approx. 32km \(Lambert conical projection\)

Availability: 1979-present

## CRUNCEP

Scale: global

Resolution: 6hr, 0.5 degree

Availability: 1901-2010

## CMIP5

Scale: varies by model

Resolution: 3 hr

Availability: 2006-2100

Currently only GFDL available. Different scenerios and ensemble members can be set via Advanced Edit.

## NLDAS

Scale: Lower 48 + buffer,

Resolution: 1 hour, .125 degree

Availability: 1980-present

## GLDAS

Scale: Global

Resolution: 3hr, 1 degree

Availability: 1948-2010

## PalEON

Scale: -100 to -60 W Lon, 35 to 50 N Latitude \(US northern hardwoods + buffer\)

Resolution: 6hr, 0.5 degree

Availability: 850-2010

## FluxnetLaThuile

Scale: site

Resolution: 30 or 60 min

Availability: varies by site  http:\/\/www.fluxdata.org\/DataInfo\/Dataset%20Doc%20Lib\/SynthDataSummary.aspx

Notes: 2007 synthesis. Fluxnet2015 supercedes this for sites that have been updated

## Geostreams

Scale: site

Resolution: varies

Availability: varies by site

Notes: This is a protocol, not a single archive. The PEcAn functions currently default to querying [https://terraref.ncsa.illinois.edu/clowder/api/geostreams], which requires login and contains data from only two sites (Urbana IL and Maricopa AZ). However the interface can be used with any server that supports the [Geostreams API](https://opensource.ncsa.illinois.edu/confluence/display/CATS/Geostreams+API).

