---
title: "BioCro PEcAn workflow"
output: html_vignette
vignette: >
  %\VignetteIndexEntry{BioCro PEcAn workflow}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r warning=FALSE}
library(PEcAn.all)
```
### Load PEcAn settings file.

Open and read in settings file for PEcAn run.


```{r warning=FALSE}
library(PEcAn.settings)
settings <- read.settings(system.file("extdata/pecan.biocro.xml", package = "PEcAn.BIOCRO"))
settings$sensitivity.analysis <- settings$ensemble
model <- settings$model$type
settings <- prepare.settings(settings)

```
### Query database for trait data

```{r warning=FALSE,cache=TRUE}
library(PEcAn.DB)
settings$pfts <- get.trait.data(settings$pfts, settings$model$type, settings$run$dbfiles, settings$database$bety, settings$meta.analysis$update)# Query the trait database for data and priors
```

### Run Meta-analysis
```{r warning=FALSE,cache=TRUE}
run.meta.analysis(settings$pfts, settings$meta.analysis$iter, settings$meta.analysis$random.effects$on, settings$meta.analysis$threshold, settings$run$dbfiles, settings$database$bety)
```



```{r warning=FALSE,cache=TRUE}
run.write.configs(settings, settings$database$bety$write)
```

```{r warning=FALSE,cache=TRUE}
## load met data
PEcAn.workflow::start_model_runs(settings, settings$database$bety$write)         # Start ecosystem model runs
```

```{r warning=FALSE,cache=TRUE}
convert.outputs(model = settings$model$name, settings = settings)

run.sensitivity.analysis()      # Run sensitivity analysis and variance decomposition on model output

run.ensemble.analysis()		      # Run ensemble analysis on model output. 
                                # OPTIONAL: run.ensemble.analysis(plot.timeseries=TRUE) to get an esemble 
                                # time-series output for the target variables set in the PEcAn.xml file

### PEcAn workflow run complete
print("---------- PEcAn Workflow Complete ----------")
#--------------------------------------------------------------------------------------------------#
```
