* Overview

  The analysis from LeBauer et al (201x) can be reproduced, with the exception of running the ED2 Model, completely within this Virtual Machine. To run with the ED2 model, see the "advanced" section below.

** For more information about the individual modules in PEcAn, please see the [[/home/pecan/pecan/man/Module_Documentation.html][Module Documentation]]
** To run a multi-run PEcAn example from the desktop:
   1. Double-click the "Clean" icon in the lower left-hand side of the desktop before starting a new run.
   2. The settings.xml file is the PEcAn configuration file for this test run.
      * this file includes the paths to all model inputs, model executable, and database login information.
      * To start an example analysis, the file path should be set to "/home/pecan/in/ebifarm/fast/pavi.xml" and then save.
      * Definitions of the settings file contents can be found at the [[http://128.174.125.122/wiki/index.php/PECAn_Documentation:Use#Settings_File][PEcAn wiki]]
      * NB: the settings files used to generate the manuscript are in [[~/in/ebifarm/prior/pavi.xml]] and [[~/in/ebifarm/post/pavi.xml]] however, these require access to a high performance computer (See "Advanced", below) - one could copy the <run><host> settings from the [[~/Desktop/settings.xml]] file, but it would take on the order of 4 months to finish. 
   3. Right-click the Query DB module and select "open with bash". 
      * A bash terminal will open and display the output of the Query DB module 
      * The log file "querydb.log" will appear on the desktop.
      * Read the log file before proceeding to the next step.
   4. Repeat step 3 for each of the modules on the top row of the desktop.
      * A log file will appear for each module.
   5. Double-click the "Clean" module to remove output and log files 

** To run the above analysis from the terminal:
   1. Right-click on desktop and select "open terminal here"
   2. in the terminal, issue the following commands:

#+BEGIN_SRC sh
CONFIG="/home/pecan/Desktop/settings.xml"
cd /home/pecan/pecan
./bash/query.bety.sh $CONFIG
./bash/meta.analysis.sh $CONFIG
./bash/write.configs.sh $CONFIG
./bash/start.runs.sh $CONFIG
./bash/get.model.output.sh $CONFIG
./bash/sensitivity.analysis.sh $CONFIG
#+END_SRC

** To run a single ED and pecan test cases from the terminal:
*** ED
#+BEGIN_SRC sh
cd ~/testrun.ed
ed2
#+END_SRC

*** PEcAn
#+BEGIN_SRC sh
cd ~/testrun.pecan
./runall.sh
#+END_SRC

** To reproduce the manuscript

The following commands will re-generate the manuscript using output contained in the /home/pecan/manuscript/out/ebifarm/ folders named "prior" and "post":

#+BEGIN_SRC sh
cd /home/pecan/manuscript/

R CMD Sweave priors.Rnw
R CMD Sweave results.Rnw

pdflatex manuscript
pdflatex manuscript
bibtex manuscript
pdflatex manuscript
pdflatex manuscript

evince manuscript.pdf
#+END_SRC


 Note that the "start.runs" step would launch 1200 runs and take a very long time; this is intended for use with a high performance computer.

#+BEGIN_SRC sh
cd /home/pecan/pecan

for config in prior post
do
CONFIG="/home/pecan/in/ebifarm/$config/pavi.xml"
./bash/query.bety.sh $CONFIG
./bash/meta.analysis.sh $CONFIG
./bash/write.configs.sh $CONFIG
./bash/start.runs.sh $CONFIG
./bash/get.model.output.sh $CONFIG
./bash/sensitivity.analysis.sh $CONFIG
done

./bash/write.manuscript.sh ~/manuscript/

#+END_SRC
* Advanced
  A High Performance Computer is required to run the ~1200 realizations of the ED2 model required for the present analysis. Output from these runs is provided in the ~/out/ebifarm/post and ~/out/ebifarm/prior/ folders.   

** To setup runs on a server:

   1. Configure ED2 on your server 
      - [[/home/pecan/pecan/man/VM_Creation.html][instructions]] for configuring ED on an Ubuntu Server, based on setup of the present Virtual Machine
   2. to generate an ssh key pair, execute the following and follow instructions. This will allow use of a remote server without having to enter a password. 
    #+BEGIN_SRC sh
    ~/pecan/bash/sshkey.sh
    #+END_SRC
   3. change the following nodes under run/host in the [[/home/pecan/in/ebifarm/post/pavi.xml][pavi.xml]] settings file ( to appropriate values for the remote server:
     | xml node:   | name      | rundir                            | inputs               | outdir               |
     | definition: | hostname  | location of the ED run executable | met and driver files | model output  |
     | on VM       | localhost | ~/EDBRAMS/ED/run/                 | ~/edin/              | ~/out/ebifarm/prior/ | 
   4. PEcAn should run on remote server. Note: PEcAn currently supports the PBS TORQUE queuing system (e.g. jobs are started with qsub) 




      
