###  FATES BCI PDA

```
<assim.batch>
  <method>emulator</method>
  <n.knot>30</n.knot>
  <iter>10000</iter>
  <chain>3</chain>
  <param.names>
    <broadleaf_evergreen_tropical_tree>                                      
      <param>growth_resp_factor</param>
      <param>agf_bs</param>
    </broadleaf_evergreen_tropical_tree> 
  </param.names>
  <jump>
    <adapt>100</adapt>
    <adj.min>0.1</adj.min>
    <ar.target>0.3</ar.target>
  </jump>
  <inputs>
    <file>
      <path>
        <path>/fs/data1/pecan.data/input/ForestGEO_BCI_summary/BCI_AGB.csv</path>
      </path>
      <format>ForestGEO_timeseries</format>
      <input.id>1000011171</input.id>
      <likelihood>Gaussian</likelihood>
      <variable.name>
        <variable.name>AbvGrndWood</variable.name>
      </variable.name>
      <variable.id>1000000132</variable.id>
    </file>
  </inputs>
</assim.batch>
```

```{r}
workflow.id <- 1000003054
settings <- PEcAn.settings::read.settings(file.path("/fs/data2/output/",paste0("PEcAn_",workflow.id),"pecan.CONFIGS.xml"))
```


Code snippet to reopen tunnels if loose the connection and/or have to restart from PDA history
```{r}
## connection settings
## define 'pass' as Google Authenticator current password (string)
pecan     <- "/home/dietze/pecan"
sshtunnel <- file.path(pecan,"web","sshtunnel.sh")
exe_host  <- settings$host$name
data_host <- settings$host$data_hostname
user      <- settings$host$user
exeDir    <- dirname(settings$host$tunnel)
dataDir   <- dirname(settings$host$data_tunnel)

##open connections
if(!is.null(exe_host)){
  write(pass,file.path(exeDir,"password"))
  Sys.sleep(3)
  con1 <- system2(sshtunnel,c(exe_host,user,exeDir,">",file.path(exeDir,"log"),"&"))
  file.remove(file.path(exeDir,"password"))
}

if(!is.null(data_host)){
  write(pass,file.path(dataDir,"password"))
  Sys.sleep(3)
  con2 <- system2(sshtunnel,c(data_host,user,dataDir,">",file.path(dataDir,"log"),"&"))
  file.remove(file.path(dataDir,"password"))
}

## check connections
if(!file.exists(settings$host$tunnel)){
  system2("more",file.path(exeDir,"log"))
}
if(!file.exists(settings$host$data_tunnel)){
  system2("more",file.path(dataDir,"log"))
}

```

