### Mac OSX {#macosx}

These are specific notes for installing PEcAn on Mac OSX and will be referenced from the main [installing PEcAn](Installing-PEcAn) page. You will at least need to install the build environment and Postgres sections. If you want to access the database/PEcAn using a web browser you will need to install Apache. To access the database using the BETY interface, you will need to have Ruby installed.

This document also contains information on how to install the Rstudio server edition as well as any other packages that can be helpful.


#### Install build environment

##### Option 1: Homebrew

```bash
# R
brew install r
# gfortran
brew install gcc
# OpenMPI
brew install open-mpi
# szip
brew install szip
# HDF5
brew install hdf5 
## homebrew should configure hdf5 with fortran and cxx, otherwise:
## brew install hdf5 --with-fortran --with-cxx
```


##### Option 2: Download and install

```bash
# install R
# download from http://cran.r-project.org/bin/macosx/

# install gfortran 
# download from http://cran.r-project.org/bin/macosx/tools/

# install OpenMPI
curl -o openmpi-1.6.3.tar.gz http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.3.tar.gz
tar zxf openmpi-1.6.3.tar.gz
cd openmpi-1.6.3
./configure --prefix=/usr/local
make all
sudo make install
cd ..

# install szip
curl -o szip-2.1-MacOSX-intel.tar.gz ftp://ftp.hdfgroup.org/lib-external/szip/2.1/bin/szip-2.1-MacOSX-intel.tar.gz
tar zxf szip-2.1-MacOSX-intel.tar.gz
sudo mv szip-2.1-MacOSX-intel /usr/local/szip

# install HDF5

curl -o hdf5-1.8.11.tar.gz http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.11.tar.gz
tar zxf hdf5-1.8.11.tar.gz
cd hdf5-1.8.11
sed -i -e 's/-O3/-O0/g' config/gnu-flags 
./configure --prefix=/usr/local/hdf5 --enable-fortran --enable-cxx --with-szlib=/usr/local/szip
make
# make check
sudo make install
# sudo make check-install
cd ..
```

#### Install Postgres and PostGIS

##### Option 1: 

For MacOS, the Postgres.app provides Postgres with PostGIS
already installed (http://postgresapp.com/).

To run Postgres:
*	Open Postgres.app.
* In the menu bar, click the elephant icon and select “Open psql”.

##### Option 2: install using homebrew:

```bash
# optional: remove existing postgres installations with:
# brew uninstall --force postgresql

# install postgres and postgis:
brew install postgres
brew install postgis

# to run Postgres:
brew services start postgresql
```

#### Enable PostGIS

To enable PostGIS, you should start Postgres:

```bash
psql postgres
```

And then run the following commands:

```sql
##### Enable PostGIS (includes raster)
CREATE EXTENSION postgis;
##### Enable Topology
CREATE EXTENSION postgis_topology;
##### fuzzy matching needed for Tiger
CREATE EXTENSION fuzzystrmatch;
##### Enable US Tiger Geocoder
CREATE EXTENSION postgis_tiger_geocoder;
```

To check your postgis run the following command again in psql: 

```sql
SELECT PostGIS_full_version();`
```

#### Additional installs


##### Install JAGS


##### Option 1: using homebrew

```bash
brew install jags
```

##### Option 2: Download 

Download JAGS from http://sourceforge.net/projects/mcmc-jags/files/JAGS/3.x/Mac%20OS%20X/JAGS-Mavericks-3.4.0.dmg/download.


##### Install udunits

##### Option 1: Install using homebrew:

```bash
brew install udunits
```

##### Option 2: Install udunits-2 on MacOSX is done from source.

* download most recent [version of Udunits here](http://www.unidata.ucar.edu/downloads/udunits/index.jsp)
* instructions for [compiling from source](http://www.unidata.ucar.edu/software/udunits/udunits-2/udunits2.html#Obtain)

```bash
curl -o udunits-2.1.24.tar.gz ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.1.24.tar.gz
tar zxf udunits-2.1.24.tar.gz
cd udunits-2.1.24
./configure
make
sudo make install
```

#### Install DuckDB

##### Option 1: Install using homebrew

```bash
brew install duckdb
```

##### Option 2: Download and install:

For manual installation instructions, see [DuckDB installation instructions](https://duckdb.org/docs/installation/?version=stable&environment=cli&platform=macos&download_method=direct).


#### Apache Configuration

Mac does not support pdo/postgresql by default. The easiest way to install is use: http://php-osx.liip.ch/

To enable pecan to run from your webserver.
```bash
cat > /etc/apache2/others/pecan.conf << EOF
Alias /pecan ${PWD}/pecan/web
<Directory ${PWD}/pecan/web>
  DirectoryIndex index.php
  Options +All
  Require all granted
</Directory>
EOF
```

#### Ruby

The default version of Ruby should work. Or use [JewelryBox](https://jewelrybox.unfiniti.com/).

```bash
brew install ruby
```

#### Rstudio Server

For MacOS, you can download [Rstudio Desktop](http://www.rstudio.com/).

Or using homebrew:

```bash
brew install --cask rstudio
```
