### Documenting functions using `roxygen2` {#developer-roxygen}

This is the standard method for documenting R functions in PEcAn.
For detailed instructions, see one of the following resources:

* `roxygen2` [pacakge documentation](https://roxygen2.r-lib.org/)
  - [Formatting overview](https://roxygen2.r-lib.org/articles/rd.html)
  - [Markdown formatting](https://blog.rstudio.com/2017/02/01/roxygen2-6-0-0/)
  - [Namespaces](https://roxygen2.r-lib.org/articles/namespace.html) (e.g. when to use `@export`)
* From "R packages" by Hadley Wickham:
  - [Object Documentation](http://r-pkgs.had.co.nz/man.html)
  - [Package Metadata](http://r-pkgs.had.co.nz/description.html) 
  
Below is a complete template for a Roxygen documentation block.
Note that roxygen lines start with `#'`:

```r
#' Function title, in a few words
#'
#' Function description, in 2-3 sentences.
#'
#' (Optional) Package details.
#'
#' @param argument_1 A description of the argument
#' @param argument_2 Another argument to the function
#' @return A description of what the function returns.
#'
#' @author Your name <your_email@email.com>
#' @examples
#' \dontrun{
#'   # This example will NOT be run by R CMD check.
#'   # Useful for long-running functions, or functions that
#'   # depend on files or values that may not be accessible to R CMD check.
#'   my_function("~/user/my_file")
#'}
# # This example WILL be run by R CMD check
#' my_function(1:10, argument_2 = 5)
## ^^ A few examples of the function's usage
#' @export
# ^^ Whether or not the function will be "exported" (made available) to the user.
# If omitted, the function can only be used inside the package.
my_function <- function(argument_1, argument_2) {...}
```
  
Here is a complete example from the `PEcAn.utils::days_in_year()` function:

```r
#' Number of days in a year
#'
#' Calculate number of days in a year based on whether it is a leap year or not.
#'
#' @param year Numeric year (can be a vector)
#' @param leap_year Default = TRUE. If set to FALSE will always return 365
#'
#' @author Alexey Shiklomanov
#' @return integer vector, all either 365 or 366
#' @export
#' @examples
#' days_in_year(2010)  # Not a leap year -- returns 365
#' days_in_year(2012)  # Leap year -- returns 366
#' days_in_year(2000:2008)  # Function is vectorized over years
days_in_year <- function(year, leap_year = TRUE) {...}
```

To update documentation throughout PEcAn, run `make document` in the PEcAn root directory.
_Make sure you do this before opening a pull request_ --
PEcAn's automated testing (Travis) will check if any documentation is out of date and will throw an error like the following if it is:

```
These files were changed by the build process:
{...}
```



#### Updating to a new Roxygen version

For consistency across packages and machines, all PEcAn developers need to compile documentation with the same version of Roxygen. Roxygen itself will check for this and refuse to rebuild a package that was last touched by a newer version of Roxygen, but the warning it gives is very quiet and easy to miss. We take a louder approach by hardcoding the expected Roxygen version into PEcAn's Makefile and throwing a build failure if the installed Roxygen is not an exact match.

When it is time for everyone to update to a newer Roxygen, follow the same procedure we used when updating from 7.2.3 to 7.3.1, replacing version strings as appropriate:

* Before starting, work with the team to merge/close as many existing PRs as feasible -- this process touches a lot of files and is likely to create merge conflicts in other PRs.
* Edit the Makefile to change `EXPECTED_ROXYGEN_VERSION := 7.2.3` to `EXPECTED_ROXYGEN_VERSION := 7.3.1`.
* Run `make clean && make document` to be sure Roxygen has been run on all packages.
* Check the console output for warnings from Roxygen, and fix them as needed. New versions often get pickier about formatting issues that used to be considered minor.
* Run `./scripts/generate_dependencies.R` to update the version of Roxygen recorded as a Docker dependency.
* Grep the PEcAn folder for the string `7.3.1` to make sure no references were missed.
  - e.g. this time I found  a remaining `RoxygenNote: 7.2.3` in models/cable/DESCRIPTION -- Make currently skips cable, so I redocumented it manually.
* Review all changes.
  - The changes should mostly just consist of updated `RoxygenNote:` lines in all the DESCRIPTION files.
  - In all cases but extra-double-specially if any NAMESPACE files change, make sure you understand what happened rather than blindly committing the changes. Usually the new version is an improvement, but this is the time to check.
* Once all looks good, commit and push.
* Make a loud announcement, e.g. on Slack, to tell all developers to update roxygen2 on their machines as soon as the PR is merged.
