// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pinvbayes
NumericMatrix pinvbayes(int ngibbs, NumericMatrix Observed, float adapt, float adj_min, NumericMatrix p4data);
RcppExport SEXP PEcAnRTM_pinvbayes(SEXP ngibbsSEXP, SEXP ObservedSEXP, SEXP adaptSEXP, SEXP adj_minSEXP, SEXP p4dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type ngibbs(ngibbsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Observed(ObservedSEXP);
    Rcpp::traits::input_parameter< float >::type adapt(adaptSEXP);
    Rcpp::traits::input_parameter< float >::type adj_min(adj_minSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p4data(p4dataSEXP);
    __result = Rcpp::wrap(pinvbayes(ngibbs, Observed, adapt, adj_min, p4data));
    return __result;
END_RCPP
}
// prospect4
NumericVector prospect4(double N, double Cab, double Cw, double Cm, NumericMatrix p4data);
RcppExport SEXP PEcAnRTM_prospect4(SEXP NSEXP, SEXP CabSEXP, SEXP CwSEXP, SEXP CmSEXP, SEXP p4dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type Cab(CabSEXP);
    Rcpp::traits::input_parameter< double >::type Cw(CwSEXP);
    Rcpp::traits::input_parameter< double >::type Cm(CmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p4data(p4dataSEXP);
    __result = Rcpp::wrap(prospect4(N, Cab, Cw, Cm, p4data));
    return __result;
END_RCPP
}
