library('PECAn', lib.loc = '~/lib/R')
load('pecan.samps.Rdata')
yr0 <- as.numeric(system("echo $YR0", intern =TRUE))
yrf   <- as.numeric(system("echo $YRF", intern =TRUE))
date <- system("echo $DATE", intern=TRUE)
user <- system("echo $USER", intern=TRUE)
outdir <- paste('/home/scratch/pecan/',user,'/out',date,sep='')
print(outdir)
pecan.SA(M, yr0, yrf, date, outdir)
save(satables, file = paste(outdir,'/satables.Rdata', sep = ''))
