library('PECAn', lib.loc = '~/lib/R')
load('pecan.samps.Rdata')
yr0 <- system(as.numeric("echo $YR0", intern =TRUE))
yrf   <- system(as.numeric("echo $YRF", intern =TRUE))
date <- system("echo $DATE", intern=TRUE)
pecan.SA(M, yr0, yrf, date, var.id = c('agb','ssc'))
