## Input records in BETY {#NewInput}

All model input data or data used for model calibration/validation must be registered in the BETY database. 

Before creating a new Input record, you must make sure that the format type of your data is registered in the database. If you need to make a new format record, see [Creating a new format record in BETY](#NewFormat).

## Create a database file record for the input data

An input record contains all the metadata required to identify the data, however, this record does not include the location of the data file. Since the same data may be stored in multiple places, every file has its own dbfile record. 

From your BETY interface:

* Create a DBFILES entry for the path to the file
    + From the menu click RUNS then FILES
    + Click “New File”
    + Select the machine your file is located at
    + Fill in the File Path where your file is located (aka folder or directory) NOT including the name of the file itself
    + Fill in the File Name with the name of the file itself. Note that some types of input records will refer to be ALL the files in a directory and thus File Name can be blank
    + Click Update
    
## Creating a new Input record in BETY

From your BETY interface:

* Create an INPUT entry for your data
    + From the menu click RUNS then INPUTS
    + Click “New Input”
    + Select the SITE that this data is associated with the input data set
    + Other required fields are a unique name for the input, the start and end dates of the data set, and the format of the data. If the data is not in a currently known format you will need to create a NEW FORMAT and possibly a new input converter. Instructions on how to do add a converter can be found here [Input conversion]. Instructions on how to add a format record can be found [here](#NewFormat) 
    + Parent ID is an optional variable to indicated that one dataset was derived from another.
    + Click “Create”
* Associate the DBFILE with the INPUT
    + In the RUNS -> INPUTS table, search and find the input record you just created
    + Click on the EDIT icon
    + Select “View related Files”
    + In the Search window, search for the DBFILE you just created
 * Once you have found the DBFILE, click on the “+” icon to add the file
 * Click on “Update” at the bottom when you are done.
    