wdiv <- c(277, 873, 1295, 1819)
par(mfrow=c(2,2))
plot(prospect4.dat$Cab_abs, type='l')
abline(v = wdiv, col=2)
plot(prospect4.dat$Cw_abs, type='l')
abline(v = wdiv, col=2)
plot(prospect4.dat$Cm_abs, type='l')
abline(v = wdiv, col=2)
plot(do.call(prospect, prospectInits[1:4]), type='l')
abline(v = wdiv, col=2)

par(mfrow=c(1,1))