#!/bin/bash
#
# Run this file using 'qsub species_run.qsub'
#
# All lines starting with "#$" are SGE qsub commands
#

# Specify which shell to use
#$ -S /bin/bash

# Run on the current working directory
#$ -cwd

# Join standard output and error to a single file
#$ -j y

# Name the file where to redirect standard output and error
#$ -o prospbayes_log.qlog

# Send an email when the job begins and when it ends running
#$ -m be

# Whom to send the email to
#$ -M alexey.shiklomanov@gmail.com

# Set walltime limit
#$ -l h_rt=120:00:00

# Confine to "geo" cluster
#$ -q "geo*"

# Now let's keep track of some information just in case anything goes wrong

cd ../R
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "Species : $SPEC"
echo "Folder : $FOLDER"
echo "Run : $RUN"
echo "=========================================================="

# Run the R scripts
# Arguments to R script: "Spectra name" "iterations" "Folder name" "Run ID"

R --vanilla --args $SPEC $NGIBBS $FOLDER $RUN < nimble/prospectinv_nimble.R &

wait

echo "=========================================================="
echo "Finished on : $(date)"
echo "=========================================================="
