Title
============

looking at how read.output works
------

```{r, echo=FALSE, message=FALSE}
library(ncdf4)
library(ncdf)
library(PEcAn.utils)
ed2.2008 <- nc_open ('../output/PEcAn_9/out/9/2004.nc');
xx <- nc_open ('../output/PEcAn_13/out/13/2004.nc')

testdata <- NULL
var <- "NPP"
# specify the var that is interested in
for (yr in 2002:2005)
  {data1 <- read.output(run.id=1, outdir='../output/PEcAn_1/out/1',
                     start.year=yr, end.year=yr,
                     variables=var,
                     model="SIPNET")
   data2 <- list(data2=data1[[1]]+rnorm(length(data1[[1]]),0,sd(data1[[1]])/rnorm(1,5,1)))
   obst <- list(obs=data1[[1]]+rnorm(length(data1[[1]]),0,sd(data1[[1]])/rnorm(1,5,1)))
   testdatat <- data.frame(site=rep(1,length(data1[[1]])),
                          date=rep(yr,length(data1[[1]])),
                          obs=obst[[1]],
                          model1=data1[[1]],
                          model2=data2[[1]])
   testdata <- rbind(testdata,testdatat)
   }




data2 <- read.output(run.id=2, outdir='../output/PEcAn_2/out/2',
                     start.year=2008, end.year=2009,
                     variables="GPP",
                     model="ED2")
```


```{r fig.width=7, fig.height=6}

```