#!/usr/bin/env RScript

files <-
  c(
    list.files(
      path = "base",
      full.names = TRUE,
      pattern = "^DESCRIPTION$",
      recursive = TRUE
    ),
    list.files(
      path = "modules",
      full.names = TRUE,
      pattern = "^DESCRIPTION$",
      recursive = TRUE
    ),
    list.files(
      path = "models",
      full.names = TRUE,
      pattern = "^DESCRIPTION$",
      recursive = TRUE
    )
  )

## Required dependencies
pecan <- c()
depends <- c()
docker <- c()
remotes <- c()
d <- purrr::walk(files,
                 function(x) {
                   # load DESCRIPTION file
                   d <- desc::desc(file=x)
                   deps <- d$get_deps()[['package']]

                   # PEcAn dependencies
                   y <- deps[grepl('^PEcAn.', deps)]
                   p <- d$get_field('Package')
                   f <- dirname(x)
                   pecan[[p]] <<- f
                   depends[[f]] <<- y

                   # Dockerfile dependencies
                   z <- y['package']
                   z <- deps[!grepl('^PEcAn.', deps)]
                   docker <<- unique(c(docker, z))

                   # Dockerfile remote dependencies
                   if (!purrr::is_empty(d$get_remotes())) {
                     deps <- d$get_remotes()
                     github <- gsub('github::', '', deps[grepl('^github::', deps)])
                     remotes <<- unique(c(remotes, github))

                     bad <- deps[!grepl('^github::', deps)]
                     if (!purrr::is_empty(bad)) {
                       print(bad)
                     }
                   }
                 } )

# write for makefile
cat('# autogenerated', file = 'Makefile.depends', sep = '\n', append = FALSE)
for (name in names(depends)) {
  if (name == 'models/template') next
  x <- paste0('$(call depends,', name, '): |')
  for (p in depends[[name]]) {
    # TEMP HACK: Don't declare known circular deps in utils Suggests
    if (name == "base/utils" && p == "PEcAn.DB") next
    if (name == "base/utils" && p == "PEcAn.settings") next
    if (name == "base/utils" && p == "PEcAn.data.atmosphere") next
    if (name == "base/utils" && p == "PEcAn.data.land") next
    x <- paste0(x, ' .install/', pecan[[p]])
  }
  cat(x, file = 'Makefile.depends', sep = '\n', append = TRUE)
}

# write for dockerfile
cat('#!/bin/bash',
    '# autogenerated do not edit',
    '# use scripts/generate.dockerfile.depends',
    '',
    paste('install2.r -e -s', paste(sort(docker), sep="", collapse=" \\\n    ")),
    '',
    paste('installGithub.r', paste(sort(remotes), sep="", collapse=" \\\n    ")),
    file = 'docker/depends/pecan.depends', sep = '\n', append = FALSE)
