#!/usr/bin/env Rscript

# force sorting
if (capabilities("ICU")) {
  icuSetCollate(locale = "en_US.UTF-8")
} else {
  print("Can not force sorting, this could result in unpredicted results.")
}

# following modules will be ignored
ignore <- c("modules/data.mining")

files <-
  c(
    list.files(
      path = "base",
      full.names = TRUE,
      pattern = "^DESCRIPTION$",
      recursive = TRUE
    ),
    list.files(
      path = "modules",
      full.names = TRUE,
      pattern = "^DESCRIPTION$",
      recursive = TRUE
    ),
    list.files(
      path = "models",
      full.names = TRUE,
      pattern = "^DESCRIPTION$",
      recursive = TRUE
    )
  )

## Required dependencies
pecan <- c()
depends <- c()
docker <- c()
remotes <- c()
d <- purrr::walk(
  files,
  function(x) {
    f <- dirname(x)
    if (f %in% ignore) return()

    # load DESCRIPTION file
    d <- desc::desc(file = x)
    deps <- d$get_deps()[["package"]]

    # PEcAn dependencies
    y <- deps[grepl("^PEcAn.", deps)]
    p <- d$get_field("Package")
    pecan[[p]] <<- f
    depends[[f]] <<- y

    # Dockerfile dependencies
    z <- y["package"]
    z <- deps[!grepl("^PEcAn.", deps)]
    docker <<- unique(c(docker, z))

    # Dockerfile remote dependencies
    if (!purrr::is_empty(d$get_remotes())) {
      deps <- d$get_remotes()
      github <- gsub("github::", "", deps[grepl("^github::", deps)])
      remotes <<- unique(c(remotes, github))

      bad <- deps[!grepl("^github::", deps)]
      if (!purrr::is_empty(bad)) {
       print(bad)
      }
    }
  }
)

# write for makefile
cat("# autogenerated", file = "Makefile.depends", sep = "\n", append = FALSE)
for (name in names(depends)) {
  x <- paste0("$(call depends,", name, "): |")
  for (p in depends[[name]]) {
    # TEMP HACK: Don't declare known circular deps in utils Suggests
    if (name == "base/utils" && p == "PEcAn.DB") next
    if (name == "base/utils" && p == "PEcAn.settings") next
    if (name == "base/utils" && p == "PEcAn.data.atmosphere") next
    if (name == "base/utils" && p == "PEcAn.data.land") next
    x <- paste0(x, " .install/", pecan[[p]])
  }
  cat(x, file = "Makefile.depends", sep = "\n", append = TRUE)
}

# write for dockerfile
cat("#!/bin/bash",
    "# autogenerated do not edit",
    "# use scripts/generate.dockerfile.depends",
    "",
    "# stop on error",
    "set -e",
    "",
    "# Don\'t use X11 for rgl",
    "RGL_USE_NULL=TRUE",
    "RLIB=${R_LIBS_USER:-/usr/local/lib/R/site-library}",
    "",
    "# install remotes first in case packages are references in dependencies",
    paste0(
      "installGithub.r \\\n    ",
      paste(sort(remotes), sep = "", collapse = " \\\n    ")),
    "",
    "# install all packages (depends, imports, suggests)",
    paste0(
      "install2.r -e -s -l \"${RLIB}\" -n -1\\\n    ",
      paste(sort(docker), sep = "", collapse = " \\\n    ")),
    file = "docker/depends/pecan.depends", sep = "\n", append = FALSE)
