#!/usr/bin/env Rscript

## Parse the dependencies of each PEcAn package as listed in DESCRIPTION files,
##    and update two scripts to match:
## * Makefile.depends, which tracks the dependencies between PEcAn packages
##    so that Make can install them in the correct order
## * docker/depends/pecan.depends.R. which preinstalls non-PEcAn dependencies
##    on the Docker image (or on other systems if you call it directly).
## Run this script after each time you change a DESCRIPTION,
##    and commit any resulting changes to Makefile.depends or pecan.depends.R





# Get remote refs from a package description,
# formatted for install_github.
# @param pkg_desc as read by `desc::desc`
# @return vector of remote refs,
#   with names set to their (inferred) package names
extract_remotes <- function(pkg_desc) {
  remote_sources <- pkg_desc$get_remotes()
  non_gh <- !grepl("^github::", remote_sources)
  if (any(non_gh)) {
      warning(
        "Found `Remotes` address pointing to non-Github repo: ",
        remote_sources[non_gh],
        "pecan.depends.R only supports github remotes so far, ",
        "so skipping.")
  }

  sub("^github::", "", remote_sources[!non_gh])
}


# Read DESCRIPTION file, return a list of:
#   strings `pkgname`, `dirname`
#   character vectors `pecan_deps`, `gh_deps`
#   data frame `deps`, with columns
#     `type`, `package`, `version`, `needed_by_dir`, `is_pecan`, `is_remote`
parse_desc <- function(path) {
  d <- desc::desc(file = path)
  deps <- d$get_deps()
  deps$needed_by_dir <- dirname(path)

  # Find packages listed as remote
  remote_sources <- extract_remotes(d)
  # deps$is_remote <- deps$package %in% names(remote_sources)

  list(
    mapping = data.frame(
      package = d$get_field("Package"),
      package_dir = dirname(path)),
    remotes = remote_sources,
    roxygen_version = d$get_field("RoxygenNote"),
    deps = deps)
}



# force sorting to hopefully write lines in same order on every machine
if (capabilities("ICU")) {
  icuSetCollate(locale = "en_US.UTF-8")
} else {
  print("Can not force sorting, this could result in unpredicted results.")
}

# Find all PEcAn packages...
files <- list.files(
  path = c("base", "modules", "models"),
  full.names = TRUE,
  pattern = "^DESCRIPTION$",
  recursive = TRUE
)
# ...but don't do anything with these ones
ignore <- c("modules/data.mining")
files <- files[!(dirname(files) %in% ignore)]


# Read all DESCRIPTIONS and compile all deps into one list
pkgs_parsed <- purrr::map(files, parse_desc)
deps <- pkgs_parsed |>
  purrr:::map_dfr("deps") |>
  # ignore R version requirements (e.g. "Depends: R (>= 3.2.0)")
  dplyr::filter(package != "R") |>
  dplyr::mutate(is_pecan = grepl("^PEcAn", package)) |>
  dplyr::select(package, version, needed_by_dir, tidyselect::everything())

# Add Roxygen, used to build all packages but not declared as a dependency
roxy <- pkgs_parsed |>
  purrr::map_dfr(
    ~c(needed_by_dir = .$mapping$package_dir, version = .$roxygen_version)) |>
  dplyr::mutate(
    package = "roxygen2",
    version = paste("==", version),
    type = "Roxygen",
    is_pecan = FALSE)
deps <- deps |>
  rbind(roxy) |>
  dplyr::arrange(package, version, needed_by_dir, .locale = "en_US")

# Save these for use at install time
write.csv(deps, "docker/depends/pecan_package_dependencies.csv", row.names = FALSE)


# Map out dependencies between PEcAn packages, write to makefile
pecan_name_map <- purrr::map_dfr(pkgs_parsed, "mapping")
pecan_deps <- deps |>
  dplyr::filter(is_pecan) |>
  dplyr::left_join(pecan_name_map, by = "package") |>
  dplyr::group_by(needed_by_dir) |>
  dplyr::summarize(
    dep_list = paste0(".install/", sort(unique(package_dir)), collapse = " "),
    call_txt = paste0("$(call depends,", unique(needed_by_dir), "): | ", dep_list),
    .groups = "drop") |>
  dplyr::pull(call_txt)

cat(
  c("# autogenerated", pecan_deps),
  file = "Makefile.depends",
  sep = "\n",
  append = FALSE)


# list all the GitHub remotes mentioned by any package,
# to attempt installation from these at start of Docker build
remote_repos <- sapply(pkgs_parsed, \(x)x$remotes) |>
  unlist() |>
  sort() |>
  writeLines("docker/depends/pecan_deps_from_github.txt")

