---
title: "FIA allometeries"
author: "Michael Dietze, Joshua Mantooth , Adrien Finzi"
date: '`r Sys.Date()`'
output: html_document
---

#Abstract




#Introduction

Allometric equations are in near constant use for a variety of applications, from fine-scale inventories for research purposes, to carbon budget closure at flux towers, to carbon accounting under LULUCF and REDD+, to inversions of remote sensing, to drivers of regional and global ecosystem models, to national forest inventories.

At a fine-scale, the uncertainties in allometric relationships can be enormous, both due to parametric uncertainties and from random tree-to-tree variability, however this uncertainty is rarely propagated into further analyses.

For the US we have the benefit of both a detailed national forest inventory, and a compilation of allometric equations [Jenkins et al., 2003, 2004]. However, the existing synthetic allomeries generated by Jenkins are not sufficient for many users. For example, they lump species into grouping that may not reflect the needs of different user communities, which may require equations at either a coarser or finer functional or phylogenetic resolution. In addition, they don't provide a full accounting of uncertainties, which are critical for both research and carbon accounting. For example, the current approach doen't account for systematic and random variability in allometric equations covariance.  Most importantly most users of allometric equations don’t know when and where allometries will be robust versus when they will be a dominate source of uncertainty. The relative importance allometric uncertainty is expect to vary with plot size and spatial scale, as conventional wisdom treats allometric uncertainty as a form of sampling uncertainty that will average out with large sample sizes. While this may be true for the ‘residual’ error in allometries, there are also systematic components to allometric uncertainty, such as due to site-to-site variability and interspecific variability when working with functional group allometries, which are not expected to average out in the same manner. Furthermore, because biomass increases rapidly as a function of DBH, the sampling uncertainty in the number of large trees in a stand, landscape, or region can have a disproportionate impact on carbon budgets.

##Key objectives:
	Develop Bayesian approach to synthesizing allometric equations (and new data) which can easily be run on any taxonomic grouping, component, and w/ or w/out random effects ADD SPP RANDOM EFFECTS
	Compare these equations to those in the Jenkins synthesis: Same spp groupings, diff breakdown of uncertainties, relative importance of site- and spp-variability (DIC)
	Compare to alternative species groupings (e.g. global model PFTs, ED PFTs, PalEON Genera, Harvard Forest). Illustrate the change in parameter and predictive uncertainties at the tree scale
	In estimating biomass at what scales does each source of uncertainty dominate:  individual variation, parameter error, random effects, FIA stand/sampling. 
	Using FIA, apply HB allometry at a variety of scales from subplot, plot, and then progressively higher spatial aggregations (start w/ 1 degree, add additional if there’s any indication that there’s SWITCHING in the source of uncertainty that matters)
	Using large mapped stand data, do a similar multi-scale analysis to evaluate how much the sampling vs allometry trade-off changes as a function of plot size (we know FIA subplots are too small).

#Methods

##Jenkins database

Within the U.S. large numbers of allometric relationships have been generated over the last YY years by both the ecological and forestry communities. For this work we build upon a large compilation of such equations compiled by the US Forest Service.

[[JOSH: Describe database, components, equations, etc.  Check the lit of papers citing this to make sure we’re not missing something new or important]]

### Estimation of standard error from R2

One challenge with the Jenkins compilation is that it reports R2 or correlation coefficients for each equation, but does not report the residual error, which is a critical component if we want to incorporate this uncertainty. It is also critical for imputing the missing diameter and biomass data, which is necessary because not only are we missing other important statistics (the uncertainties and covariances in the regression parameters) but we're also using a diverse array of allometric equations which need to be converted to a single functional form. Fortunately it is possible to approximate the residual error, ε, based on the R2 and the variance of the function itself.
R^2=1-Var(ϵ)/Var(Y) =Var(f(X))/(Var(f(X))+Var(ϵ))
SE=√(Var(ϵ) )= √(Var(f(X))  (1-R^2)/R^2 )  

For the special case of uniformly distributed X and a linear model this has an analytical solution
SE= √(β^(2(b-a)^2 )/12  (1-R^2)/R^2 )
However for the general case Var(f(X)) can be easily numerically approximated by simulating a large set of random X values. The estimation of the residual SE will obviously be sensitive to the choice of probability distribution function for X, and thus this introduces an important and often unverifiable assumption, but for the case of allometric relationships the assumption of a uniform distribution is consistent which the type of strategic sampling that is most often undertaken.

## Hierarchical statistical model

This model builds upon the previous work by [Dietze et al., 2008]


### Case 1: “global” model

This version just fits a Bayesian log-log linear regression through the combined data

Y ~ N(Xβ_g,σ_g^2)
σ_g^2~ IG(s_1,s_2)
β_g~N(μ_0,V_0 )
where X = log(DBH) and Y = log(biomassk) for the kth component

### Case 2: ‘site-effect’ model

Y_j  ~ N(X_j β_j,σ_j^2)
σ_j^2~IG(s_1,s_2 )
β_j~N_2 (μ,Τ)
μ~N_2 (μ_0,V_0)
Τ~IW(v,S)
Where the default priors are s1=s2=0.1, mu0=[0.2,8/3], V0=diag(100),v=0.1,s=diag(0.1)

In both cases the X and Y data are simulated from the equations in the database in their original units, and then transformed to cm and kg respectively. There are a diversity of functional forms used, and in addition in some of the original equations X was squared diameter or circumference rather than DBH.

### Case 3: ‘species-effect’ model [MIKE or JOSH]

### Case 4: ‘species- and site-effect’ model [MIKE or JOSH]

## Comparison to Jenkins composite allometries

JOSH: Build PFT list objects for Jenkins groupings (Tables 1 and 3), put in Dropbox

Fit all 4 HB models to same species groupings as Jenkins et al 2003 Table 4 for total aboveground biomass. Use model selection to assess importance of site and species variability. Plot regression lines from HB and Jenkins with CI and PI. Jenkins lacks parameter uncertainty but has a RMSE, HB full model has 4 possible intervals. Assess difference in mean and uncertainties. 

 

## Effects of species aggregation

Compare to alternative species groupings (e.g. global model PFTs, ED PFTs, PalEON Genera, Harvard Forest). Illustrate the change in parameter and predictive uncertainties at the tree scale


## Effect of spatial scale: US Forest Inventory

In estimating biomass at what scales does each source of uncertainty dominate:  individual variation, parameter error, random effects, FIA stand/sampling. 

### Describe FIA

Using FIA, apply HB allometry at a variety of scales from subplot, plot, and then progressively higher spatial aggregations (start w/ 1 degree, add additional if there’s any indication that there’s SWITCHING in the source of uncertainty that matters)


## Effects of plot size

Using large mapped stand data, do a similar multi-scale analysis to evaluate how much the sampling vs allometry trade-off changes as a function of plot size (we know FIA subplots are too small).


# Results/Discussion

## Comparison to Jenkins composite allometries


## Effects of species aggregation


## Effects of plot size


## Future directions
	Update allometric database and then perform OSSE to determine how additional allometric destructive sampling should be done
	guidance to the community on how to reduce these uncertainties. Three aspects: how to sample (size class, within vs across site), what to sample (taxonomic/functional deficiencies), and how large an inventory must be in order to overcome individual variability.
	Change in biomass through time: discussion of the individual effect / autocorrelation problem

# Conclusions


# Acknowledgements

Grants: PEcAn, Brown Dog, PalEON, Gap Macrosystems

Harvard Forest Carbon Synthesis Team

# Citations

 
Dietze, M. C., M. S. Wolosin, and J. S. Clark (2008), Capturing diversity and interspecific variability in allometries: A hierarchical approach, For. Ecol. Manage., 256(11), 1939–1948, doi:10.1016/j.foreco.2008.07.034. [online] Available from: http://linkinghub.elsevier.com/retrieve/pii/S0378112708005793
Jenkins, J. C., D. C. Chojnacky, L. S. Heath, and R. A. Birdsey (2003), National-Scale Biomass Estimators for United States Tree Species, For. Sci., 49(1), 12–35. [online] Available from: http://www.ingentaconnect.com/content/saf/fs/2003/00000049/00000001/art00002
Jenkins, J. C., D. C. Chojnacky, L. S. Heath, and R. A. Birdsey (2004), Comprehensive Database of Diameter-based Biomass Regressions for North American Tree Species, America (NY)., (cm).

# Tables

Table 1: HB parameter estimates for Jenkins groupings, all 4 models w/ DICs

Supplemental Tables: Parameter estimates for alternative species aggregations.


# Figure Legends

Figure 1 A-J: Comparison of HB to Jenkins allometries

Figure 2: species aggregation (how to plot?)

Figure 3: uncertainty partitioning vs spatial scale

Figure 4: uncertainty partitioning vs plot size.


# Supplement:

Usage of PEcAn.allometry

	Pull PEcAn from github.com/PEcAnProject/pecan
	Navigate to  pecan/modules
	Build the allometries package (R CMD build allometry)
	Within R, library(PEcAn.allometries)
	Read help, especially for AllomAve
	Define your PFTs as a list based on USFS species codes (spcd)

pfts = list(FAGR = data.frame(spcd=531,name="FAgr",acronym="FAGR"))

## example of a PFT with multiple species (LH = late hardwood)
## note that if you're just using Jenkins the acronym column is optional
pfts = list(LH = data.frame(spcd = c(531,318),acronym=c("FAGR","ACSA3")))

	run AllomAve

allom.stats = AllomAve(pfts,ngibbs=500)

	If you want to run with a response variable other than the default (components = 6; stem biomass), look up the relevant component IDs in data(allom.components). Note that if you specify multiple PFTs (as a list) and multiple components (as a vector) then AllomAve will generate allometries for all PFT x component combinations

