# SiBCASA

| Model Information ||
| -- | -- |
| Home Page | |
| Source Code | Contact Kevin Schaefer at (kevin.schaefer[at]nsidc.org|
| License |  |
| Authors | Kevin Shaefer|
| PEcAn Integration |Tony Gardella, Yasin Elshorbany |

**Introduction**

SiBCASA was created from the combination of the Carnegie-Ames_Stanford Approach (CASA) and the Simple Biosphere(SiB) model.They have added other features, including dynamic allocation of GPP for the growth and maintance of leaves, roots, and wood andd explicit calculation of autotrophic respiration.

Schaefer, Kevin, et al. "The combined Simple Biosphere/Carnegie-Ames-Stanford Approach (SiBCASA) Model." J. Geophys. Res 113: G03034.

**PEcAn configuration file additions**


**Model specific input files**

Software libraries-  
PGI 16.5 or later
https://www.pgroup.com/products/community.htm

NETCDF 3.6.0

Input - 
Driver data: Made to use CRUNCEP data by default.
Param File 
Initial Condition File

**Model configuration files**
The namel_sibdrv is the namelist file that controls input and output file locations.


**Installation notes**
Update $PATH to the netcdf library version 3.6 (compiled with the same PGI Fortran compiler) in: 
PEcAn/sim_setup/Makefile     &
PEcAn/SiB/sibcasa_arctic4/Makefile

Change paths in:
Line 379:  /SiB/sibcasa_ arctic4/read_ti.F90
Line 260, 273, 286: /SiB/sibcasa_ arctic4/sibdrv_read_ncep2.F90
Update $PATH variables in: /SiB/sibcasa_arctic4/sibmerg.in
        IMPORTANT: update “fmt_type='sing_proc'” even if running on parallel computing system, since the file names will otherwise be incompatible with the outputted data..check

Compile code: in     ~/SiB/sibcasa_arctic4/
`Make clean`
`Make`



**VM**
Currently Not Avialable on the VM
