## Updating PEcAn Code and Bety Database {#updatebety}

Release notes for all releases can be found [here](https://github.com/PecanProject/pecan/releases).

This page will only list any steps you have to do to upgrade an existing system. When updating PEcAn it is highly encouraged to update BETY. You can find instructions on how to do this, as well on how to update the database in the [Updating BETYdb](https://pecan.gitbooks.io/betydb-documentation/content/updating_betydb_when_new_versions_are_released.html) gitbook page.


### Updating PEcAn {#pecan-make}

The latest version of PEcAn code can be obtained from the PEcAn repository on GitHub:

```bash
cd pecan        # If you are not already in the PEcAn directory
git pull
```

The PEcAn build system is based on GNU Make. 
The simplest way to install is to run `make` from inside the PEcAn directory.
This will update the documentation for all packages and install them, as well as all required dependencies.

For more control, the following `make` commands are available:

* `make document` -- Use `devtools::document` to update the documentation for all package. 
Under the hood, this uses the `roxygen2` documentation system.

* `make install` -- Install all packages and their dependnencies using `devtools::install`. 
By default, this only installs packages that have had their code changed and any dependent packages.

* `make check` -- Perform a rigorous check of packages using `devtools::check`

* `make test` -- Run all unit tests (based on `testthat` package) for all packages, using `devtools::test`

* `make clean` -- Remove the make build cache, which is used to track which packages have changed.
Cache files are stored in the `.doc`, `.install`, `.check`, and `.test` subdirectories in the PEcAn main directory.
Running `make clean` will force the next invocation of `make` commands to operate on all PEcAn packages, regardless of changes.

The following are some additional `make` tricks that may be useful:

* Install, check, document, or test a specific package -- `make .<cmd>/<pkg-dir>`; e.g. `make .install/utils` or `make .check/modules/rtm`

* Force `make` to run, even if package has not changed -- `make -B <command>`

* Run `make` commands in parallel -- `make -j<ncores>`; e.g. `make -j4 install` to install packages using four parallel processes. Note that packages containing compiled code (e.g. PEcAn.RTM, PEcAn.BASGRA) might fail when `j` is greater than 1, because of limitations in the way R calls `make` internally while compiling them. See [GitHub issue 1976](https://github.com/PecanProject/pecan/issues/1976) for more details.

All instructions for the `make` build system are contained in the `Makefile` in the PEcAn root directory.
For full documentation on `make`, see the man pages by running `man make` from a terminal.
