##' Runs heirarchical meta-analysis of plant trait data 
##'
##' \code{pecan.ma} runs a heirarchical Bayes meta-analytical model.
##' This model combines prior information with data from studies on the particular species or group of interest.
##' Data that is incorporated into the meta-analysis include the mean (Y), sample size (n),
##' and precision (obs.prec). 
##' Where a set of data includes more than one level of treatment, comes from more than one site,
##' or comes from both field and greenhouse studies, these variables are included as random (treatment, site)
##' or fixed (greenhouse) effects. 
##' The pecan.ma function writes a model for each specific data set and prior using the write.ma.model()
##' function to modify the ma.model.template.bug generic model. 
##' 
##' 
##' @title Trait Meta-analysis 
##' @param trait.data list of dataframes, one per trait for which data is available, generated by call to query.bety.traits()
##' @param prior.distns dataframe of prior distributions generated by call to query.bety.priors()
##' @param taupriors priors on variance parameters, can be scaled as needed with data mean
##' @param j.iter number of mcmc samples
##' @param settings list of settings from settings file
##' @param outdir 
##' @param overdispersed TRUE by default, if set to FALSE, data mean will be used as starting point for MCMC chains (use with caution)
##' @return four chains with 5000 total samples from posterior 
##' @author David LeBauer, Michael C. Dietze
##'
##' @examples
##' prior.distns <- query.bety.priors('ebifarm.c4crop', c('SLA', 'c2n_leaf'))
##' trait.data <- query.bety.traits('938', c('SLA', 'c2n_leaf'))
##' pecan.ma(prior.distns, trait.data, 25000)
pecan.ma <- function(trait.data, prior.distns, taupriors, j.iter, settings, outdir, overdispersed = TRUE){
  
  madata <- list()
  ## Meta-analysis for each trait
  mcmc.object <- list() #  initialize output list of mcmc objects for each trait
  mcmc.mat    <- list()
  
  ## Set inputs for jags.model()
  j.chains <- 4

  ## Convert R distributions to JAGS distributions
  jagspriors <- r2bugs.distributions(prior.distns)
  ## log the mcmc chain parameters
  sink(file = paste(outdir,'meta-analysis.log',sep=""), split = TRUE)
  cat(paste( 'Each meta-analysis will be run with: \n',
            j.iter, ' total iterations,\n',
            j.chains, ' chains, \n',
            'a burnin of ', j.iter/2, ' samples,\n',
            ', \nthus the total number of samples will be ', j.chains*(j.iter/2),'\n', sep = '')
      )

  for(trait.name in names(trait.data)) {
    jagsprior <- jagspriors[trait.name, c('distn', 'parama', 'paramb', 'n')]
    colnames(jagsprior) <- c("distn", "a", "b", "n")
    prior <- prior.distns[trait.name, c('distn', 'parama', 'paramb', 'n')]
    colnames(prior) <- c("distn", "a", "b", "n")

    writeLines(paste('################################################'))
    writeLines(paste('------------------------------------------------'))
    writeLines(paste('starting meta-analysis for:\n\n', trait.name,'\n'))
    writeLines(paste('------------------------------------------------'))
    data <- trait.data[[trait.name]]
    data <- data[, which(!colnames(data) %in% c("cite","trait_id","se"))] ## remove citation and other unneeded co lumns
    data <- data[order(data$site,data$trt),]#not sure why, but required for JAGS model

    ##check for excess missing data
    if(all(is.na(data$obs.prec))){
      writeLines("NO ERROR STATS PROVIDED, DROPPING RANDOM EFFECTS")
      data$site = rep(1,nrow(data))
      data$trt  = rep(0,nrow(data))
    }

    if(!is.null(settings$meta.analysis$random.effects)){
      if(!as.logical(settings$meta.analysis$random.effects)){
        data$site = rep(1,nrow(data))
        data$trt  = rep(0,nrow(data))
      }
    }
    
    #print out some data summaries to check
    writeLines(paste('prior for ', trait.name, ' (using R parameterization):\n',
                prior$distn, '(',prior$a, ', ', prior$b, ')', sep = ''))
    writeLines(paste('data max:', max(data$Y), '\ndata min:', min(data$Y), '\nmean:', signif(mean(data$Y),3), '\nn:', length(data$Y)))
    writeLines('stem plot of data points')
    writeLines(paste(stem(data$Y)))
    if(any(!is.na(data$obs.prec)) && all(!is.infinite(data$obs.prec))){
      writeLines('stem plot of obs.prec:')
      writeLines(paste(stem(data$obs.prec^2)))
    } else {
      writeLines(paste('no estimates of SD for', trait.name))
    }
    # determine what factors to include in meta-analysis
    model.parms <- list(ghs  = length(unique(data$ghs)),
                        site = length(unique(data$site)),
                        trt  = length(unique(data$trt)))
    # define regression model
    reg.parms   <- list(ghs  = 'beta.ghs[ghs[k]]', #beta.o will be included by default
                        site = 'beta.site[site[k]]',
                        trt  = 'beta.trt[trt[k]]')
    if(sum(model.parms>1)==0) {
      reg.model <- ''
    } else {
      reg.model <- paste('+', reg.parms[model.parms > 1], collapse = " ")
    }
        
    ## generate list of parameters for jags to follow and produce mcmc output for
    vars <- c( 'beta.o', 'sd.y') 
    for (x in c('ghs', 'site', 'trt')) {
      if(model.parms[[x]] == 1) {
        data <- data[, which(names(data) != x)]
      } else {
        data <- data
        if(x!='ghs') {
          vars <- c(vars, paste('sd.', x, sep = ''))
        }
        # m <- min(model.parms[[x]], 5)
        m <- model.parms[[x]]
        for (i in 1:m) {
          if(i == 1 && x == 'site') {
            vars <- c(vars, 'beta.site[1]')
          }
          if (i > 1) {
            vars <- c(vars, paste('beta.', x, '[', i, ']', sep=''))
          }
        }
      }
    }

    madata[[trait.name]] <- data
    jag.model.file <-  paste(outdir, trait.name, ".model.bug",sep="")  # file to store model

    write.ma.model (modelfile = paste(settings$pecanDir,'rscripts/ma.model.template.bug',sep=""),
                    outfile = jag.model.file,
                    reg.model = reg.model,
                    jagsprior$distn, jagsprior$a, jagsprior$b,
                    n     = length ( data$Y ),
                    trt.n = model.parms[['trt']],
                    site.n= model.parms[['site']],
                    ghs.n = model.parms[['ghs']],
                    tauA  = taupriors$tauA,
                    tauB  = taupriors$tauB[trait.name])

    if(overdispersed == TRUE){
      ## overdispersed chains
      j.inits <- function(chain) list("beta.o" = do.call(paste('q',prior$dist,sep=''),
                                        list(chain * 1/(j.chains + 1), prior$a, prior$b)),
                                      .RNG.seed = chain,
                                      .RNG.name = "base::Mersenne-Twister")
    } else if (overdispersed == FALSE) {
      ## chains fixed at data mean - used if above code does not converge,
      ## invalidates assumptions about convergence, e.g. Gelman-Rubin diagnostic
      j.inits <- function(chain) list("beta.o" = mean(data$Y))
    }
    
    j.model   <- jags.model (file = jag.model.file,
                             data = data,
                             #n.adapt = 100, #will burn in below
                             n.chains = j.chains,
                             init =  j.inits)


    jags.out   <- coda.samples ( model = j.model,
                                variable.names = vars,
                                n.iter = j.iter,
                                thin = max(c(2,j.iter/(5000*2))))
    print(summary(jags.out))
    
    jags.out.trunc <- window(jags.out, start = j.iter/2)
 
    mcmc.object[[trait.name]] <- jags.out.trunc
  }
  save(madata, file = paste(outdir,'madata.Rdata',sep=""))
  sink()
  return(mcmc.object)
}
