#-------------------------------------------------------------------------------
# Copyright (c) 2012 University of Illinois, NCSA.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the 
# University of Illinois/NCSA Open Source License
# which accompanies this distribution, and is available at
# http://opensource.ncsa.illinois.edu/license.html
#-------------------------------------------------------------------------------
library(XML)
library(ncdf4)

# ----------------------------------------------------------------------
# COMMAND LINE ARGUMENTS
# ----------------------------------------------------------------------
# arguments are --args year variable
args     <- commandArgs(trailingOnly = TRUE)
datafile <- args[1]
year     <- args[2]
xvar     <- 'time'
yvar     <- args[3]
width    <- as.numeric(args[4])
height   <- as.numeric(args[5])
filename <- args[6]

# ----------------------------------------------------------------------
# SETUP
# ----------------------------------------------------------------------
settings.file <- Sys.getenv('PECANSETTINGS')
settings.xml <- xmlParse(settings.file)
settings <- xmlToList(settings.xml)

# year=2006
# xvar='time'
# yvar="GPP"
# width=800
# height=600
# filename="plot.png"

# ----------------------------------------------------------------------
# PRIVATE FUNCTIONS
# ----------------------------------------------------------------------
data.fetch <- function(var, nc, fun=mean) {
	# get a specific set of values from the HDF data
	#
	# Args:
	#   var:    the variable to extract from the hdf data
	#   nc:
	#   time:
	#   fun:    the function to apply to the data at the same time
	#
	# Returns:
	#   values extracted from the nc data
	if (var == "time") {
		val <- unique(floor(nc$dim[['time']]$vals))
		attr(val, "lbl") <- "Day of the year"
		return(val)
	}
	
	# some precomputations
	indices  <- 0:length(nc$dim[['time']]$vals)
	aggrlist <- list(floor(nc$dim[['time']]$vals))
	
	# aggregate the data
	data <- ncvar_get(nc, var)
	val <- aggregate(data[indices], by=aggrlist, FUN=fun)$x
	
	# get the label
	title <- nc$var[[var]]$longname
	units <- nc$var[[var]]$units
	if ((title == "") && (units == "")) {
		attr(val, "lbl") <- "Unknown"
	} else if (title == "") {
		attr(val, "lbl") <- paste("Unknown in ", units)
	} else if (units == "") {
		attr(val, "lbl") <- title
	} else {
		attr(val, "lbl") <- paste(title, "in", units)
	}
	
	# done
	return(val)
}

# ----------------------------------------------------------------------
# MAIN FUNCTIONS
# ----------------------------------------------------------------------
########################## CREATE PLOT #################################
##' Load the tower dataset and create a plot.
##' @name plot.hdf5
##'
##' \code{plot.hdf5} loads the tower data from an HDF5 file generated by
##' ED and will plot the values against one another. The default is for
##' the given variable to be plotted against time.
##'
##' @param datafile the specific datafile to use.
##' @param year the specific year to use.
##' @param yvar the variable to plot along the y-axis.
##' @param xvar the variable to plot along the x-axis, by default time is
##' used.
##' @param the width of the image generated, default is 800 pixels.
##' @param the height of the image generated, default is 600 pixels.
##' @param filename is the name of the file name that is geneated.
##' @param settings the pecan.xml file loaded.
plot.netcdf <- function(datafile, year, yvar, xvar='time', width=800, height=600, filename, settings) {	
	# open netcdf file
	nc <- nc_open(file.path(settings$run$host$outdir, datafile))
	
	# compute variables
	xval_mean <- data.fetch(xvar, nc, mean)
	xval_max  <- data.fetch(xvar, nc, max)
	xval_min  <- data.fetch(xvar, nc, min)
	yval_mean <- data.fetch(yvar, nc, mean)
	yval_max  <- data.fetch(yvar, nc, max)
	yval_min  <- data.fetch(yvar, nc, min)
	
	# done with netcdf file
	nc_close(nc)
	
	# setup plot (needs to be done before removing of NA since that removes attr as well).
	png(filename=filename, width=width, height=height)
	plot.new()
	title(xlab=attr(xval_mean, "lbl"))
	title(ylab=attr(yval_mean, "lbl"))
	if (xvar == "time") {
		title(main=paste(nc$var[[yvar]]$longname, "for", year))
	} else {
		title(main=paste(xvar, "VS", yvar, "for", year))
	}
	
	# remove all NA's
	removeme <- unique(c(which(is.na(xval_min)), which(is.na(yval_min)), which(is.na(xval_mean)), which(is.na(yval_mean)), which(is.na(xval_max)), which(is.na(yval_max))))
	if (length(removeme) > 0) {
		xval_mean <- xval_mean[-removeme]
		xval_max  <- xval_max[-removeme]
		xval_min  <- xval_min[-removeme]
		yval_mean <- yval_mean[-removeme]
		yval_max  <- yval_max[-removeme]
		yval_min  <- yval_min[-removeme]
	}
	
	# combine
	xvals <- c(xval_max, rev(xval_min))
	yvals <- c(yval_max, rev(yval_min))
	
	# plot actual data
	plot.window(xlim=c(min(xvals), max(xvals)), ylim=c(min(yvals), max(yvals)))
	polygon(c(xval_max, rev(xval_min)), c(yval_max, rev(yval_min)), col="gray", border="black")
	points(xval_mean, yval_mean, col="black", pch=20)
	
	# draw axis and box
	axis(1)
	axis(2)
	box()
	dev.off()
}

plot.netcdf(datafile, year, yvar, xvar, width, height, filename, settings);

